/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

/*tasks.named<org.springframework.boot.gradle.tasks.bundling.BootJar>("bootJar") {
    archiveBaseName.set("ProjectForge-application")
    archiveVersion.set("8.0.0")
    archiveClassifier.set("")
}*/

dependencies {
    api(libs.org.springframework.boot.starter.web)
    api(project(":projectforge-wicket"))
    api(project(":projectforge-rest"))
    api(project(":projectforge-webapp"))
    api(project(":projectforge-caldav"))
    api(libs.com.googlecode.lanterna.lanterna)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.org.reflections.reflections)
    runtimeOnly(project(":org.projectforge.plugins.datatransfer"))
    runtimeOnly(project(":org.projectforge.plugins.ihk"))
    runtimeOnly(project(":org.projectforge.plugins.licensemanagement"))
    runtimeOnly(project(":org.projectforge.plugins.liquidityplanning"))
    runtimeOnly(project(":org.projectforge.plugins.marketing"))
    runtimeOnly(project(":org.projectforge.plugins.memo"))
    runtimeOnly(project(":org.projectforge.plugins.merlin"))
    runtimeOnly(project(":org.projectforge.plugins.banking"))
    runtimeOnly(project(":org.projectforge.plugins.skillmatrix"))
    runtimeOnly(project(":org.projectforge.plugins.todo"))
    testImplementation(project(":projectforge-commons-test"))
}

description = "projectforge-application"
