/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":projectforge-common"))
    api(libs.org.springframework.boot.starter.jersey)
    api(libs.org.glassfish.jaxb.jaxb.core)
}

description = "projectforge-model"
