// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.address.AddressbookDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const ADDRESSBOOK_METADATA = {
  entity: "AddressbookDO",
  historizable: true,
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "addressbook.description",
      required: false,
      maxLength: 4000,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    owner: {
      dataType: "USER",
      i18nKey: "addressbook.owner",
      required: false,
    },
    title: {
      dataType: "STRING",
      i18nKey: "addressbook.title",
      required: true,
      maxLength: 1000,
    },
  },
} as const satisfies EntityMetadata;
