// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.address.AddressDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const ADDRESS_METADATA = {
  entity: "AddressDO",
  historizable: true,
  fields: {
    addressStatus: {
      dataType: "STRING",
      i18nKey: "address.addressStatus",
      required: true,
      enumValues: [
        {
          value: "UPTODATE",
          i18nKey: "address.addressStatus.uptodate",
        },
        {
          value: "OUTDATED",
          i18nKey: "address.addressStatus.outdated",
        },
        {
          value: "LEAVED",
          i18nKey: "address.addressStatus.leaved",
        },
      ],
    },
    addressText: {
      dataType: "STRING",
      i18nKey: "address.addressText",
      required: false,
      maxLength: 255,
    },
    addressText2: {
      dataType: "STRING",
      i18nKey: "address.addressText2",
      required: false,
      maxLength: 255,
    },
    birthName: {
      dataType: "STRING",
      i18nKey: "address.birthName",
      required: false,
      maxLength: 255,
    },
    birthday: {
      dataType: "DATE",
      i18nKey: "address.birthday",
      required: false,
    },
    businessPhone: {
      dataType: "STRING",
      i18nKey: "address.phone",
      required: false,
      maxLength: 255,
    },
    city: {
      dataType: "STRING",
      i18nKey: "address.city",
      required: false,
      maxLength: 255,
    },
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 5000,
    },
    communicationLanguage: {
      dataType: "LOCALE",
      i18nKey: "address.communicationLanguage",
      required: false,
    },
    contactStatus: {
      dataType: "STRING",
      i18nKey: "address.contactStatus",
      required: true,
      enumValues: [
        {
          value: "ACTIVE",
          i18nKey: "address.contactStatus.active",
        },
        {
          value: "NON_ACTIVE",
          i18nKey: "address.contactStatus.nonActive",
        },
        {
          value: "UNINTERESTING",
          i18nKey: "address.contactStatus.uninteresting",
        },
        {
          value: "PERSONA_INGRATA",
          i18nKey: "address.contactStatus.personaIngrata",
        },
        {
          value: "DEPARTED",
          i18nKey: "address.contactStatus.departed",
        },
      ],
    },
    country: {
      dataType: "STRING",
      i18nKey: "address.country",
      required: false,
      maxLength: 255,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    division: {
      dataType: "STRING",
      i18nKey: "address.division",
      required: false,
      maxLength: 255,
    },
    email: {
      dataType: "STRING",
      i18nKey: "email",
      required: false,
      maxLength: 255,
    },
    fax: {
      dataType: "STRING",
      i18nKey: "address.phoneType.fax",
      required: false,
      maxLength: 255,
    },
    fingerprint: {
      dataType: "STRING",
      i18nKey: "address.fingerprint",
      required: false,
      maxLength: 255,
    },
    firstName: {
      dataType: "STRING",
      i18nKey: "firstName",
      required: false,
      maxLength: 255,
    },
    form: {
      dataType: "STRING",
      i18nKey: "address.form",
      required: true,
      enumValues: [
        {
          value: "MISTER",
          i18nKey: "address.form.mister",
        },
        {
          value: "MISS",
          i18nKey: "address.form.miss",
        },
        {
          value: "COMPANY",
          i18nKey: "address.form.company",
        },
        {
          value: "MISC",
          i18nKey: "address.form.misc",
        },
        {
          value: "UNKNOWN",
          i18nKey: "address.form.unknown",
        },
      ],
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    mobilePhone: {
      dataType: "STRING",
      i18nKey: "address.phoneType.mobile",
      required: false,
      maxLength: 255,
    },
    name: {
      dataType: "STRING",
      i18nKey: "name",
      required: true,
      maxLength: 255,
    },
    organization: {
      dataType: "STRING",
      i18nKey: "organization",
      required: false,
      maxLength: 255,
    },
    positionText: {
      dataType: "STRING",
      i18nKey: "address.positionText",
      required: false,
      maxLength: 255,
    },
    postalAddressText: {
      dataType: "STRING",
      i18nKey: "address.addressText",
      required: false,
      maxLength: 255,
    },
    postalAddressText2: {
      dataType: "STRING",
      i18nKey: "address.addressText2",
      required: false,
      maxLength: 255,
    },
    postalCity: {
      dataType: "STRING",
      i18nKey: "address.city",
      required: false,
      maxLength: 255,
    },
    postalCountry: {
      dataType: "STRING",
      i18nKey: "address.country",
      required: false,
      maxLength: 255,
    },
    postalState: {
      dataType: "STRING",
      i18nKey: "address.state",
      required: false,
      maxLength: 255,
    },
    postalZipCode: {
      dataType: "STRING",
      i18nKey: "address.zipCode",
      required: false,
      maxLength: 255,
    },
    privateAddressText: {
      dataType: "STRING",
      i18nKey: "address.addressText",
      required: false,
      maxLength: 255,
    },
    privateAddressText2: {
      dataType: "STRING",
      i18nKey: "address.addressText2",
      required: false,
      maxLength: 255,
    },
    privateCity: {
      dataType: "STRING",
      i18nKey: "address.city",
      required: false,
      maxLength: 255,
    },
    privateCountry: {
      dataType: "STRING",
      i18nKey: "address.country",
      required: false,
      maxLength: 255,
    },
    privateEmail: {
      dataType: "STRING",
      i18nKey: "email",
      required: false,
      maxLength: 255,
    },
    privateMobilePhone: {
      dataType: "STRING",
      i18nKey: "address.phoneType.mobile",
      required: false,
      maxLength: 255,
    },
    privatePhone: {
      dataType: "STRING",
      i18nKey: "address.phone",
      required: false,
      maxLength: 255,
    },
    privateState: {
      dataType: "STRING",
      i18nKey: "address.state",
      required: false,
      maxLength: 255,
    },
    privateZipCode: {
      dataType: "STRING",
      i18nKey: "address.zipCode",
      required: false,
      maxLength: 255,
    },
    publicKey: {
      dataType: "STRING",
      i18nKey: "address.publicKey",
      required: false,
      maxLength: 20000,
    },
    state: {
      dataType: "STRING",
      i18nKey: "address.state",
      required: false,
      maxLength: 255,
    },
    title: {
      dataType: "STRING",
      i18nKey: "address.title",
      required: false,
      maxLength: 255,
    },
    website: {
      dataType: "STRING",
      i18nKey: "address.website",
      required: false,
      maxLength: 255,
    },
    zipCode: {
      dataType: "STRING",
      i18nKey: "address.zipCode",
      required: false,
      maxLength: 255,
    },
  },
} as const satisfies EntityMetadata;
