// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.plugins.marketing.AddressCampaignDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const ADDRESS_CAMPAIGN_METADATA = {
  entity: "AddressCampaignDO",
  historizable: true,
  fields: {
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    title: {
      dataType: "STRING",
      i18nKey: "title",
      required: false,
      maxLength: 1000,
    },
    values: {
      dataType: "STRING",
      i18nKey: "values",
      required: false,
      maxLength: 1000,
    },
  },
} as const satisfies EntityMetadata;
