// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.AuftragsPositionDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const AUFTRAGS_POSITION_METADATA = {
  entity: "AuftragsPositionDO",
  historizable: true,
  fields: {
    art: {
      dataType: "STRING",
      i18nKey: "fibu.auftrag.position.art",
      required: false,
      enumValues: [
        {
          value: "CHANGE_REQUEST",
          i18nKey: "fibu.auftrag.position.art.change_request",
        },
        {
          value: "DAUERNDE_LEISTUNG",
          i18nKey: "fibu.auftrag.position.art.dauernde_leistung",
        },
        {
          value: "WARTUNG",
          i18nKey: "fibu.auftrag.position.art.wartung",
        },
        {
          value: "NEUENTWICKLUNG",
          i18nKey: "fibu.auftrag.position.art.neuentwicklung",
        },
      ],
    },
    bemerkung: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    forecastType: {
      dataType: "STRING",
      i18nKey: "fibu.auftrag.forecastType",
      required: false,
      tooltipI18nKey: "fibu.auftrag.forecastType.info",
      enumValues: [
        {
          value: "CURRENT_MONTH",
          i18nKey: "fibu.auftrag.forecastType.currentMonth",
        },
        {
          value: "FOLLOWING_MONTH",
          i18nKey: "fibu.auftrag.forecastType.followingMonth",
        },
      ],
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    modeOfPaymentType: {
      dataType: "STRING",
      i18nKey: "fibu.modeOfPayment",
      required: false,
      enumValues: [
        {
          value: "FIXED",
          i18nKey: "fibu.modeOfPayment.type.fixed",
        },
        {
          value: "MONTHLY",
          i18nKey: "fibu.modeOfPayment.type.monthly",
        },
        {
          value: "QUARTERLY",
          i18nKey: "fibu.modeOfPayment.type.quarterly",
        },
        {
          value: "ANNUAL",
          i18nKey: "fibu.modeOfPayment.type.annual",
        },
      ],
    },
    nettoSumme: {
      dataType: "DECIMAL",
      i18nKey: "fibu.auftrag.nettoSumme",
      required: false,
    },
    number: {
      dataType: "INT",
      i18nKey: "fibu.auftrag.position",
      required: false,
    },
    paymentType: {
      dataType: "STRING",
      i18nKey: "fibu.auftrag.position.paymenttype",
      required: false,
      enumValues: [
        {
          value: "FESTPREISPAKET",
          i18nKey: "fibu.auftrag.position.paymenttype.festpreispaket",
        },
        {
          value: "TIME_AND_MATERIALS",
          i18nKey: "fibu.auftrag.position.paymenttype.time_and_materials",
        },
        {
          value: "PAUSCHALE",
          i18nKey: "fibu.auftrag.position.paymenttype.pauschale",
        },
      ],
    },
    periodOfPerformanceBegin: {
      dataType: "DATE",
      i18nKey: "fibu.periodOfPerformance.from",
      required: false,
    },
    periodOfPerformanceEnd: {
      dataType: "DATE",
      i18nKey: "fibu.periodOfPerformance.to",
      required: false,
    },
    periodOfPerformanceType: {
      dataType: "STRING",
      i18nKey: "fibu.periodOfPerformance",
      required: false,
      enumValues: [
        {
          value: "SEEABOVE",
          i18nKey: "fibu.periodOfPerformance.type.seeabove",
        },
        {
          value: "OWN",
          i18nKey: "fibu.periodOfPerformance.type.own",
        },
      ],
    },
    personDays: {
      dataType: "DECIMAL",
      i18nKey: "projectmanagement.personDays",
      required: false,
    },
    status: {
      dataType: "STRING",
      i18nKey: "status",
      required: false,
      enumValues: [
        {
          value: "IN_ERSTELLUNG",
          i18nKey: "fibu.auftrag.status.in_erstellung",
        },
        {
          value: "POTENZIAL",
          i18nKey: "fibu.auftrag.status.potenzial",
        },
        {
          value: "GELEGT",
          i18nKey: "fibu.auftrag.status.gelegt",
        },
        {
          value: "LOI",
          i18nKey: "fibu.auftrag.status.loi",
        },
        {
          value: "BEAUFTRAGT",
          i18nKey: "fibu.auftrag.status.beauftragt",
        },
        {
          value: "ABGESCHLOSSEN",
          i18nKey: "fibu.auftrag.status.abgeschlossen",
        },
        {
          value: "ABGELEHNT",
          i18nKey: "fibu.auftrag.status.abgelehnt",
        },
        {
          value: "ERSETZT",
          i18nKey: "fibu.auftrag.status.ersetzt",
        },
        {
          value: "ESKALATION",
          i18nKey: "fibu.auftrag.status.eskalation",
        },
        {
          value: "OPTIONAL",
          i18nKey: "fibu.auftrag.status.optional",
        },
      ],
    },
    task: {
      dataType: "TASK",
      i18nKey: "task",
      required: false,
    },
    titel: {
      dataType: "STRING",
      i18nKey: "fibu.auftrag.title",
      required: false,
      maxLength: 255,
    },
    vollstaendigFakturiert: {
      dataType: "BOOLEAN",
      i18nKey: "fibu.auftrag.vollstaendigFakturiert",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
