// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.AuftragDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const AUFTRAG_METADATA = {
  entity: "AuftragDO",
  fields: {
    angebotsDatum: {
      dataType: "DATE",
      i18nKey: "fibu.auftrag.angebot.datum",
      required: false,
    },
    attachmentsLastUserAction: {
      dataType: "STRING",
      i18nKey: "attachment",
      required: false,
      maxLength: 10000,
    },
    beauftragungsDatum: {
      dataType: "DATE",
      i18nKey: "fibu.auftrag.beauftragungsdatum",
      required: false,
    },
    bemerkung: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    bindungsFrist: {
      dataType: "DATE",
      i18nKey: "fibu.auftrag.bindungsFrist",
      required: false,
    },
    contactPerson: {
      dataType: "USER",
      i18nKey: "contactPerson",
      required: false,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    entscheidungsDatum: {
      dataType: "DATE",
      i18nKey: "fibu.auftrag.entscheidung.datum",
      required: false,
    },
    erfassungsDatum: {
      dataType: "DATE",
      i18nKey: "fibu.auftrag.erfassung.datum",
      required: false,
    },
    forecastType: {
      dataType: "STRING",
      i18nKey: "fibu.auftrag.forecastType",
      required: false,
      tooltipI18nKey: "fibu.auftrag.forecastType.info",
      enumValues: [
        {
          value: "CURRENT_MONTH",
          i18nKey: "fibu.auftrag.forecastType.currentMonth",
        },
        {
          value: "FOLLOWING_MONTH",
          i18nKey: "fibu.auftrag.forecastType.followingMonth",
        },
      ],
    },
    headOfBusinessManager: {
      dataType: "USER",
      i18nKey: "fibu.headOfBusinessManager",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    kundeText: {
      dataType: "STRING",
      i18nKey: "fibu.kunde.text",
      required: false,
      maxLength: 1000,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    nummer: {
      dataType: "INT",
      i18nKey: "fibu.auftrag.nummer",
      required: true,
    },
    periodOfPerformanceBegin: {
      dataType: "DATE",
      i18nKey: "fibu.periodOfPerformance.from",
      required: false,
    },
    periodOfPerformanceEnd: {
      dataType: "DATE",
      i18nKey: "fibu.periodOfPerformance.to",
      required: false,
    },
    probabilityOfOccurrence: {
      dataType: "INT",
      i18nKey: "fibu.probabilityOfOccurrence",
      required: false,
    },
    projectManager: {
      dataType: "USER",
      i18nKey: "fibu.projectManager",
      required: false,
    },
    referenz: {
      dataType: "STRING",
      i18nKey: "fibu.common.customer.reference",
      required: false,
      maxLength: 255,
    },
    salesManager: {
      dataType: "USER",
      i18nKey: "fibu.salesManager",
      required: false,
    },
    status: {
      dataType: "STRING",
      i18nKey: "status",
      required: false,
      enumValues: [
        {
          value: "IN_ERSTELLUNG",
          i18nKey: "fibu.auftrag.status.in_erstellung",
        },
        {
          value: "POTENZIAL",
          i18nKey: "fibu.auftrag.status.potenzial",
        },
        {
          value: "GELEGT",
          i18nKey: "fibu.auftrag.status.gelegt",
        },
        {
          value: "LOI",
          i18nKey: "fibu.auftrag.status.loi",
        },
        {
          value: "BEAUFTRAGT",
          i18nKey: "fibu.auftrag.status.beauftragt",
        },
        {
          value: "ABGESCHLOSSEN",
          i18nKey: "fibu.auftrag.status.abgeschlossen",
        },
        {
          value: "ABGELEHNT",
          i18nKey: "fibu.auftrag.status.abgelehnt",
        },
        {
          value: "ERSETZT",
          i18nKey: "fibu.auftrag.status.ersetzt",
        },
        {
          value: "ESKALATION",
          i18nKey: "fibu.auftrag.status.eskalation",
        },
        {
          value: "OPTIONAL",
          i18nKey: "fibu.auftrag.status.optional",
        },
      ],
    },
    statusBeschreibung: {
      dataType: "STRING",
      i18nKey: "fibu.auftrag.statusBeschreibung",
      required: false,
      maxLength: 4000,
    },
    titel: {
      dataType: "STRING",
      i18nKey: "fibu.auftrag.title",
      required: false,
      maxLength: 1000,
    },
  },
} as const satisfies EntityMetadata;
