// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.AuftragsPositionDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const AUFTRAGS_POSITION_METADATA = {
  entity: "AuftragsPositionDO",
  historizable: true,
  fields: {
    art: {
      dataType: "STRING",
      i18nKey: "fibu.auftrag.position.art",
      required: false,
      enumValues: [
        {
          value: "CHANGE_REQUEST",
          i18nKey: "fibu.auftrag.position.art.change_request",
        },
        {
          value: "DAUERNDE_LEISTUNG",
          i18nKey: "fibu.auftrag.position.art.dauernde_leistung",
        },
        {
          value: "WARTUNG",
          i18nKey: "fibu.auftrag.position.art.wartung",
        },
        {
          value: "NEUENTWICKLUNG",
          i18nKey: "fibu.auftrag.position.art.neuentwicklung",
        },
      ],
    },
    bemerkung: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    forecastType: {
      dataType: "STRING",
      i18nKey: "fibu.auftrag.forecastType",
      required: false,
      tooltipI18nKey: "fibu.auftrag.forecastType.info",
      enumValues: [
        {
          value: "CURRENT_MONTH",
          i18nKey: "fibu.auftrag.forecastType.currentMonth",
        },
        {
          value: "FOLLOWING_MONTH",
          i18nKey: "fibu.auftrag.forecastType.followingMonth",
        },
      ],
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    nettoSumme: {
      dataType: "DECIMAL",
      i18nKey: "fibu.auftrag.nettoSumme",
      required: false,
    },
    paymentType: {
      dataType: "STRING",
      i18nKey: "fibu.auftrag.position.paymenttype",
      required: false,
      enumValues: [
        {
          value: "FESTPREISPAKET",
          i18nKey: "fibu.auftrag.position.paymenttype.festpreispaket",
        },
        {
          value: "TIME_AND_MATERIALS",
          i18nKey: "fibu.auftrag.position.paymenttype.time_and_materials",
        },
        {
          value: "PAUSCHALE",
          i18nKey: "fibu.auftrag.position.paymenttype.pauschale",
        },
      ],
    },
    personDays: {
      dataType: "DECIMAL",
      i18nKey: "projectmanagement.personDays",
      required: false,
    },
    status: {
      dataType: "STRING",
      i18nKey: "fibu.auftrag.position.status",
      required: false,
      enumValues: [
        {
          value: "IN_ERSTELLUNG",
          i18nKey: "fibu.auftrag.status.in_erstellung",
        },
        {
          value: "POTENZIAL",
          i18nKey: "fibu.auftrag.status.potenzial",
        },
        {
          value: "GELEGT",
          i18nKey: "fibu.auftrag.status.gelegt",
        },
        {
          value: "LOI",
          i18nKey: "fibu.auftrag.status.loi",
        },
        {
          value: "BEAUFTRAGT",
          i18nKey: "fibu.auftrag.status.beauftragt",
        },
        {
          value: "ABGESCHLOSSEN",
          i18nKey: "fibu.auftrag.status.abgeschlossen",
        },
        {
          value: "ABGELEHNT",
          i18nKey: "fibu.auftrag.status.abgelehnt",
        },
        {
          value: "ERSETZT",
          i18nKey: "fibu.auftrag.status.ersetzt",
        },
        {
          value: "ESKALATION",
          i18nKey: "fibu.auftrag.status.eskalation",
        },
        {
          value: "OPTIONAL",
          i18nKey: "fibu.auftrag.status.optional",
        },
      ],
    },
    titel: {
      dataType: "STRING",
      i18nKey: "fibu.auftrag.title",
      required: false,
      maxLength: 255,
    },
  },
} as const satisfies EntityMetadata;
