// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.plugins.banking.BankAccountDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const BANK_ACCOUNT_METADATA = {
  entity: "BankAccountDO",
  fields: {
    bank: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.bank",
      required: true,
      maxLength: 1000,
    },
    bic: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.bic",
      required: false,
      maxLength: 1000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    iban: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.iban",
      required: false,
      maxLength: 1000,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    importSettings: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.importSettings",
      required: false,
      maxLength: 10000,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    name: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.name",
      required: true,
      maxLength: 1000,
    },
  },
} as const satisfies EntityMetadata;
