// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.plugins.banking.BankAccountRecordDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const BANK_ACCOUNT_RECORD_METADATA = {
  entity: "BankAccountRecordDO",
  historizable: true,
  fields: {
    amount: {
      dataType: "DECIMAL",
      i18nKey: "plugins.banking.account.record.amount",
      required: false,
    },
    bic: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.bic",
      required: false,
      maxLength: 1000,
    },
    checksum: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.record.checksum",
      required: false,
      maxLength: 1000,
      tooltipI18nKey: "plugins.banking.account.record.checksum.info",
    },
    collectionReference: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.record.collectionReference",
      required: false,
      maxLength: 4000,
    },
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    currency: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.record.currency",
      required: false,
      maxLength: 4000,
    },
    customerReference: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.record.customerReference",
      required: false,
      maxLength: 4000,
    },
    date: {
      dataType: "DATE",
      i18nKey: "plugins.banking.account.record.date",
      required: false,
    },
    debteeId: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.record.debteeId",
      required: false,
      maxLength: 4000,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    iban: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.iban",
      required: false,
      maxLength: 1000,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    info: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.record.info",
      required: false,
      maxLength: 4000,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    mandateReference: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.record.mandateReference",
      required: false,
      maxLength: 4000,
    },
    receiverSender: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.record.receiverSender",
      required: false,
      maxLength: 4000,
    },
    subject: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.record.subject",
      required: false,
      maxLength: 4000,
    },
    type: {
      dataType: "STRING",
      i18nKey: "plugins.banking.account.record.type",
      required: false,
      maxLength: 4000,
    },
    valueDate: {
      dataType: "DATE",
      i18nKey: "plugins.banking.account.record.valueDate",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
