// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.plugins.banking.BankAccountBalanceDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const BANK_ACCOUNT_BALANCE_METADATA = {
  entity: "BankAccountBalanceDO",
  fields: {
    amount: {
      dataType: "DECIMAL",
      i18nKey: "plugins.banking.account.record.amount",
      required: false,
    },
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    date: {
      dataType: "DATE",
      i18nKey: "plugins.banking.account.record.date",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
