// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.book.BookDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const BOOK_METADATA = {
  entity: "BookDO",
  fields: {
    abstractText: {
      dataType: "STRING",
      i18nKey: "book.abstract",
      required: false,
      maxLength: 4000,
    },
    attachmentsLastUserAction: {
      dataType: "STRING",
      i18nKey: "attachment",
      required: false,
      maxLength: 10000,
    },
    authors: {
      dataType: "STRING",
      i18nKey: "book.authors",
      required: false,
      maxLength: 1000,
    },
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 1000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    editor: {
      dataType: "STRING",
      i18nKey: "book.editor",
      required: false,
      maxLength: 255,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    isbn: {
      dataType: "STRING",
      i18nKey: "book.isbn",
      required: false,
      maxLength: 255,
    },
    keywords: {
      dataType: "STRING",
      i18nKey: "book.keywords",
      required: false,
      maxLength: 1024,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    lendOutBy: {
      dataType: "USER",
      i18nKey: "book.lendOutBy",
      required: false,
    },
    lendOutComment: {
      dataType: "STRING",
      i18nKey: "book.lendOutNote",
      required: false,
      maxLength: 1024,
    },
    lendOutDate: {
      dataType: "DATE",
      i18nKey: "date",
      required: false,
    },
    publisher: {
      dataType: "STRING",
      i18nKey: "book.publisher",
      required: false,
      maxLength: 255,
    },
    signature: {
      dataType: "STRING",
      i18nKey: "book.signature",
      required: false,
      maxLength: 255,
    },
    status: {
      dataType: "STRING",
      i18nKey: "status",
      required: true,
      enumValues: [
        {
          value: "PRESENT",
          i18nKey: "book.status.present",
        },
        {
          value: "MISSED",
          i18nKey: "book.status.missed",
        },
        {
          value: "DISPOSED",
          i18nKey: "book.status.disposed",
        },
        {
          value: "UNKNOWN",
          i18nKey: "book.status.unknown",
        },
      ],
    },
    title: {
      dataType: "STRING",
      i18nKey: "book.title",
      required: true,
      maxLength: 255,
    },
    type: {
      dataType: "STRING",
      i18nKey: "book.type",
      required: false,
      enumValues: [
        {
          value: "AUDIO_BOOK",
          i18nKey: "book.type.audiobook",
        },
        {
          value: "BOOK",
          i18nKey: "book.type.book",
        },
        {
          value: "EBOOK",
          i18nKey: "book.type.ebook",
        },
        {
          value: "MAGAZINE",
          i18nKey: "book.type.magazine",
        },
        {
          value: "ARTICLE",
          i18nKey: "book.type.article",
        },
        {
          value: "NEWSPAPER",
          i18nKey: "book.type.newspaper",
        },
        {
          value: "PERIODICAL",
          i18nKey: "book.type.periodical",
        },
        {
          value: "FILM",
          i18nKey: "book.type.film",
        },
        {
          value: "SOFTWARE",
          i18nKey: "book.type.software",
        },
        {
          value: "THESIS",
          i18nKey: "book.type.thesis",
        },
        {
          value: "MISC",
          i18nKey: "book.type.misc",
        },
      ],
    },
    yearOfPublishing: {
      dataType: "STRING",
      i18nKey: "book.yearOfPublishing",
      required: false,
      maxLength: 4,
    },
  },
} as const satisfies EntityMetadata;
