// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.kost.BuchungssatzDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const BUCHUNGSSATZ_METADATA = {
  entity: "BuchungssatzDO",
  historizable: true,
  fields: {
    beleg: {
      dataType: "STRING",
      i18nKey: "fibu.buchungssatz.beleg",
      required: false,
      maxLength: 255,
    },
    betrag: {
      dataType: "DECIMAL",
      i18nKey: "fibu.common.betrag",
      required: true,
    },
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    kost1: {
      dataType: "COST1",
      i18nKey: "fibu.kost1",
      required: false,
    },
    kost2: {
      dataType: "COST2",
      i18nKey: "fibu.kost2",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    menge: {
      dataType: "STRING",
      i18nKey: "fibu.buchungssatz.menge",
      required: false,
      maxLength: 255,
    },
    satznr: {
      dataType: "INT",
      i18nKey: "fibu.buchungssatz.satznr",
      required: true,
    },
    sh: {
      dataType: "STRING",
      i18nKey: "finance.accountingRecord.dc",
      required: true,
      enumValues: [
        {
          value: "SOLL",
          i18nKey: "finance.accountingRecord.dc.debit",
        },
        {
          value: "HABEN",
          i18nKey: "finance.accountingRecord.dc.credit",
        },
      ],
    },
    text: {
      dataType: "STRING",
      i18nKey: "fibu.buchungssatz.text",
      required: false,
      maxLength: 255,
    },
  },
} as const satisfies EntityMetadata;
