// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.orga.ContractDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const CONTRACT_METADATA = {
  entity: "ContractDO",
  fields: {
    attachmentsLastUserAction: {
      dataType: "STRING",
      i18nKey: "attachment",
      required: false,
      maxLength: 10000,
    },
    coContractorA: {
      dataType: "STRING",
      i18nKey: "legalAffaires.contract.coContractorA",
      required: false,
      maxLength: 1000,
    },
    coContractorB: {
      dataType: "STRING",
      i18nKey: "legalAffaires.contract.coContractorB",
      required: false,
      maxLength: 1000,
    },
    contractPersonA: {
      dataType: "STRING",
      i18nKey: "legalAffaires.contract.contractPersonA",
      required: false,
      maxLength: 1000,
    },
    contractPersonB: {
      dataType: "STRING",
      i18nKey: "legalAffaires.contract.contractPersonB",
      required: false,
      maxLength: 1000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    date: {
      dataType: "DATE",
      i18nKey: "date",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    dueDate: {
      dataType: "DATE",
      i18nKey: "dueDate",
      required: false,
    },
    filing: {
      dataType: "STRING",
      i18nKey: "filing",
      required: false,
      maxLength: 1000,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    number: {
      dataType: "INT",
      i18nKey: "'C-",
      required: false,
      tooltipI18nKey: "fibu.tooltip.nummerWirdAutomatischVergeben",
    },
    reference: {
      dataType: "STRING",
      i18nKey: "fibu.common.reference",
      required: false,
      maxLength: 255,
    },
    resubmissionOnDate: {
      dataType: "DATE",
      i18nKey: "resubmissionOnDate",
      required: false,
    },
    signerA: {
      dataType: "STRING",
      i18nKey: "legalAffaires.contract.signerA",
      required: false,
      maxLength: 1000,
    },
    signerB: {
      dataType: "STRING",
      i18nKey: "legalAffaires.contract.signerB",
      required: false,
      maxLength: 1000,
    },
    signingDate: {
      dataType: "DATE",
      i18nKey: "legalAffaires.contract.signing",
      required: false,
    },
    status: {
      dataType: "STRING",
      i18nKey: "status",
      required: false,
      enumValues: [
        {
          value: "UNKNOWN",
          i18nKey: "legalAffaires.contract.status.unknown",
        },
        {
          value: "IN_PROGRESS",
          i18nKey: "legalAffaires.contract.status.inProgress",
        },
        {
          value: "IN_COORDINATION",
          i18nKey: "legalAffaires.contract.status.inCoordination",
        },
        {
          value: "COMPLETED",
          i18nKey: "legalAffaires.contract.status.completed",
        },
        {
          value: "SIGNED",
          i18nKey: "legalAffaires.contract.status.signed",
        },
        {
          value: "SUSPENDED",
          i18nKey: "legalAffaires.contract.status.suspended",
        },
        {
          value: "ESCALATED",
          i18nKey: "legalAffaires.contract.status.escalated",
        },
      ],
    },
    text: {
      dataType: "STRING",
      i18nKey: "text",
      required: false,
      maxLength: 4000,
    },
    title: {
      dataType: "STRING",
      i18nKey: "title",
      required: true,
      maxLength: 1000,
    },
    type: {
      dataType: "STRING",
      i18nKey: "legalAffaires.contract.type",
      required: false,
      maxLength: 100,
    },
    validFrom: {
      dataType: "DATE",
      i18nKey: "legalAffaires.contract.validity.from",
      required: false,
    },
    validUntil: {
      dataType: "DATE",
      i18nKey: "legalAffaires.contract.validity.until",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
