// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.CurrencyConversionRateDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const CURRENCY_CONVERSION_RATE_METADATA = {
  entity: "CurrencyConversionRateDO",
  fields: {
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    conversionRate: {
      dataType: "DECIMAL",
      i18nKey: "fibu.currencyConversion.conversionRate",
      required: true,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    inverseConversionRate: {
      dataType: "DECIMAL",
      i18nKey: "fibu.currencyConversion.inverseConversionRate",
      required: true,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    validFrom: {
      dataType: "DATE",
      i18nKey: "attr.validSince",
      required: true,
    },
  },
} as const satisfies EntityMetadata;
