// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.CurrencyPairDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const CURRENCY_PAIR_METADATA = {
  entity: "CurrencyPairDO",
  historizable: true,
  fields: {
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    sourceCurrency: {
      dataType: "STRING",
      i18nKey: "fibu.currencyPair.sourceCurrency",
      required: true,
      maxLength: 3,
      tooltipI18nKey: "fibu.currencyPair.currencyCode.tooltip",
    },
    targetCurrency: {
      dataType: "STRING",
      i18nKey: "fibu.currencyPair.targetCurrency",
      required: true,
      maxLength: 3,
      tooltipI18nKey: "fibu.currencyPair.currencyCode.tooltip",
    },
  },
} as const satisfies EntityMetadata;
