// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.plugins.datatransfer.DataTransferAreaDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const DATA_TRANSFER_AREA_METADATA = {
  entity: "DataTransferAreaDO",
  fields: {
    areaName: {
      dataType: "STRING",
      i18nKey: "plugins.datatransfer.areaName",
      required: true,
      maxLength: 100,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "plugins.datatransfer.description",
      required: false,
      maxLength: 4000,
      tooltipI18nKey: "plugins.datatransfer.description.info",
    },
    expiryDays: {
      dataType: "INT",
      i18nKey: "plugins.datatransfer.expiryDays",
      required: false,
      tooltipI18nKey: "plugins.datatransfer.expiryDays.info",
    },
    externalAccessLogs: {
      dataType: "STRING",
      i18nKey: "plugin.datatransfer.externalAccess.logs",
      required: false,
      maxLength: 10000,
    },
    externalAccessToken: {
      dataType: "STRING",
      i18nKey: "plugins.datatransfer.external.accessToken",
      required: false,
      maxLength: 100,
      tooltipI18nKey: "plugins.datatransfer.external.accessToken.info",
    },
    externalDownloadEnabled: {
      dataType: "BOOLEAN",
      i18nKey: "plugins.datatransfer.external.download.enabled",
      required: false,
      tooltipI18nKey: "plugins.datatransfer.external.download.enabled.info",
    },
    externalPassword: {
      dataType: "STRING",
      i18nKey: "plugins.datatransfer.external.password",
      required: false,
      maxLength: 100,
      tooltipI18nKey: "plugins.datatransfer.external.password.info",
    },
    externalUploadEnabled: {
      dataType: "BOOLEAN",
      i18nKey: "plugins.datatransfer.external.upload.enabled",
      required: false,
      tooltipI18nKey: "plugins.datatransfer.external.upload.enabled.info",
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    maxUploadSizeKB: {
      dataType: "INT",
      i18nKey: "plugins.datatransfer.maxUploadSize",
      required: false,
      tooltipI18nKey: "plugins.datatransfer.maxUploadSize.info",
    },
  },
} as const satisfies EntityMetadata;
