// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.EingangsrechnungDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const EINGANGSRECHNUNG_METADATA = {
  entity: "EingangsrechnungDO",
  historizable: true,
  fields: {
    bemerkung: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    besonderheiten: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.besonderheiten",
      required: false,
      maxLength: 4000,
    },
    betreff: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.betreff",
      required: false,
      maxLength: 4000,
    },
    bezahlDatum: {
      dataType: "DATE",
      i18nKey: "fibu.rechnung.bezahlDatum",
      required: false,
    },
    bic: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.bic",
      required: false,
      maxLength: 11,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    currency: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.currency",
      required: false,
      maxLength: 10,
    },
    customernr: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.customernr",
      required: false,
      maxLength: 255,
    },
    datum: {
      dataType: "DATE",
      i18nKey: "fibu.rechnung.datum",
      required: true,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    discountMaturity: {
      dataType: "DATE",
      i18nKey: "fibu.rechnung.discountMaturity",
      required: false,
    },
    discountPercent: {
      dataType: "DECIMAL",
      i18nKey: "fibu.rechnung.discountPercent",
      required: false,
    },
    discountZahlungsZielInTagen: {
      dataType: "INT",
      i18nKey: "fibu.rechnung.discountZahlungsZiel",
      required: false,
    },
    faelligkeit: {
      dataType: "DATE",
      i18nKey: "fibu.rechnung.faelligkeit",
      required: false,
    },
    iban: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.iban",
      required: false,
      maxLength: 50,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    kreditor: {
      dataType: "STRING",
      i18nKey: "fibu.common.creditor",
      required: false,
      maxLength: 255,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    paymentType: {
      dataType: "STRING",
      i18nKey: "fibu.payment.type",
      required: false,
      enumValues: [
        {
          value: "BANK_TRANSFER",
          i18nKey: "fibu.payment.type.bankTransfer",
        },
        {
          value: "DEBIT",
          i18nKey: "fibu.payment.type.debit",
        },
        {
          value: "CREDIT_CARD",
          i18nKey: "fibu.payment.type.creditCard",
        },
        {
          value: "CASH",
          i18nKey: "fibu.payment.type.cash",
        },
        {
          value: "SALARY",
          i18nKey: "fibu.payment.type.salary",
        },
        {
          value: "CREDIT",
          i18nKey: "fibu.payment.type.credit",
        },
      ],
    },
    receiver: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.receiver",
      required: false,
      maxLength: 255,
    },
    referenz: {
      dataType: "STRING",
      i18nKey: "fibu.common.reference",
      required: false,
      maxLength: 1000,
    },
    year: {
      dataType: "INT",
      i18nKey: "calendar.year",
      required: false,
      readOnly: true,
    },
    zahlBetrag: {
      dataType: "DECIMAL",
      i18nKey: "fibu.rechnung.zahlBetrag",
      required: false,
    },
    zahlungsZielInTagen: {
      dataType: "INT",
      i18nKey: "fibu.rechnung.zahlungsZiel",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
