// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.EingangsrechnungsPositionDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const EINGANGSRECHNUNGS_POSITION_METADATA = {
  entity: "EingangsrechnungsPositionDO",
  historizable: true,
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    einzelNetto: {
      dataType: "DECIMAL",
      i18nKey: "fibu.rechnung.position.einzelNetto",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    menge: {
      dataType: "DECIMAL",
      i18nKey: "fibu.rechnung.menge",
      required: false,
    },
    text: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.text",
      required: false,
      maxLength: 1000,
    },
    vat: {
      dataType: "DECIMAL",
      i18nKey: "fibu.rechnung.mehrwertSteuerSatz",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
