// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.EmployeeDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const EMPLOYEE_METADATA = {
  entity: "EmployeeDO",
  historizable: true,
  fields: {
    abteilung: {
      dataType: "STRING",
      i18nKey: "fibu.employee.division",
      required: false,
      maxLength: 255,
    },
    annualLeave: {
      dataType: "DECIMAL",
      i18nKey: "fibu.employee.urlaubstage",
      required: false,
    },
    austrittsDatum: {
      dataType: "DATE",
      i18nKey: "fibu.employee.austrittsdatum",
      required: false,
    },
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    eintrittsDatum: {
      dataType: "DATE",
      i18nKey: "fibu.employee.eintrittsdatum",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    kost1: {
      dataType: "COST1",
      i18nKey: "fibu.kost1",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    position: {
      dataType: "STRING",
      i18nKey: "address.positionText",
      required: false,
      maxLength: 244,
    },
    staffNumber: {
      dataType: "STRING",
      i18nKey: "fibu.employee.staffNumber",
      required: false,
      maxLength: 255,
    },
    status: {
      dataType: "STRING",
      i18nKey: "fibu.employee.status",
      required: false,
      enumValues: [
        {
          value: "FEST_ANGESTELLTER",
          i18nKey: "fibu.employee.status.festAngestellter",
        },
        {
          value: "BEFRISTET_ANGESTELLTER",
          i18nKey: "fibu.employee.status.befristetAngestellter",
        },
        {
          value: "FREELANCER",
          i18nKey: "fibu.employee.status.freelancer",
        },
        {
          value: "AUSHILFE",
          i18nKey: "fibu.employee.status.aushilfe",
        },
        {
          value: "STUDENTISCHE_HILFSKRAFT",
          i18nKey: "fibu.employee.status.studentischeHilfskraft",
        },
        {
          value: "STUD_ABSCHLUSSARBEIT",
          i18nKey: "fibu.employee.status.studentischeAbschlussarbeit",
        },
        {
          value: "PRAKTIKANT",
          i18nKey: "fibu.employee.status.praktikant",
        },
        {
          value: "AZUBI",
          i18nKey: "fibu.employee.status.azubi",
        },
      ],
    },
    user: {
      dataType: "USER",
      i18nKey: "fibu.employee.user",
      required: false,
    },
    weeklyWorkingHours: {
      dataType: "DECIMAL",
      i18nKey: "fibu.employee.wochenstunden",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
