// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.EmployeeValidSinceAttrDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const EMPLOYEE_VALID_SINCE_ATTR_METADATA = {
  entity: "EmployeeValidSinceAttrDO",
  fields: {
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    employee: {
      dataType: "EMPLOYEE",
      i18nKey: "fibu.employee",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    validSince: {
      dataType: "DATE",
      i18nKey: "attr.validSince",
      required: true,
    },
    value: {
      dataType: "STRING",
      i18nKey: "value",
      required: false,
      maxLength: 255,
    },
  },
} as const satisfies EntityMetadata;
