// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.EmployeeSalaryDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const EMPLOYEE_SALARY_METADATA = {
  entity: "EmployeeSalaryDO",
  historizable: true,
  fields: {
    bruttoMitAgAnteil: {
      dataType: "DECIMAL",
      i18nKey: "fibu.employee.salary.bruttoMitAgAnteil",
      required: false,
    },
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    employee: {
      dataType: "EMPLOYEE",
      i18nKey: "fibu.employee",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    month: {
      dataType: "INT",
      i18nKey: "calendar.month",
      required: false,
    },
    type: {
      dataType: "STRING",
      i18nKey: "fibu.employee.salary.type",
      required: false,
      enumValues: [
        {
          value: "GEHALT",
          i18nKey: "fibu.employee.salary.type.gehalt",
        },
        {
          value: "TANTIEME",
          i18nKey: "fibu.employee.salary.type.tantieme",
        },
        {
          value: "ZIELVEREINBARUNG",
          i18nKey: "fibu.employee.salary.type.zielvereinbarung",
        },
        {
          value: "PRAEMIE",
          i18nKey: "fibu.employee.salary.type.praemie",
        },
        {
          value: "SONDERZAHLUNG",
          i18nKey: "fibu.employee.salary.type.sonderzahlung",
        },
      ],
    },
    year: {
      dataType: "INT",
      i18nKey: "calendar.year",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
