// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.gantt.GanttChartDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const GANTT_CHART_METADATA = {
  entity: "GanttChartDO",
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    name: {
      dataType: "STRING",
      i18nKey: "gantt.name",
      required: false,
      maxLength: 1000,
    },
    owner: {
      dataType: "USER",
      i18nKey: "gantt.owner",
      required: false,
    },
    task: {
      dataType: "TASK",
      i18nKey: "task",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
