// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.framework.persistence.user.entities.GroupDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const GROUP_METADATA = {
  entity: "GroupDO",
  historizable: true,
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 1000,
    },
    groupOwner: {
      dataType: "USER",
      i18nKey: "group.owner",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    ldapValues: {
      dataType: "STRING",
      i18nKey: "ldap",
      required: false,
      maxLength: 4000,
    },
    localGroup: {
      dataType: "BOOLEAN",
      i18nKey: "group.localGroup",
      required: false,
    },
    name: {
      dataType: "STRING",
      i18nKey: "name",
      required: false,
      maxLength: 100,
    },
    organization: {
      dataType: "STRING",
      i18nKey: "organization",
      required: false,
      maxLength: 100,
    },
  },
} as const satisfies EntityMetadata;
