// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.humanresources.HRPlanningEntryDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const HR_PLANNING_ENTRY_METADATA = {
  entity: "HRPlanningEntryDO",
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "hr.planning.description",
      required: false,
      maxLength: 4000,
    },
    fridayHours: {
      dataType: "DECIMAL",
      i18nKey: "calendar.shortday.friday",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    mondayHours: {
      dataType: "DECIMAL",
      i18nKey: "calendar.shortday.monday",
      required: false,
    },
    priority: {
      dataType: "STRING",
      i18nKey: "hr.planning.priority",
      required: false,
      enumValues: [
        {
          value: "LEAST",
          i18nKey: "priority.least",
        },
        {
          value: "LOW",
          i18nKey: "priority.low",
        },
        {
          value: "MIDDLE",
          i18nKey: "priority.middle",
        },
        {
          value: "HIGH",
          i18nKey: "priority.high",
        },
        {
          value: "HIGHEST",
          i18nKey: "priority.highest",
        },
      ],
    },
    probability: {
      dataType: "INT",
      i18nKey: "hr.planning.probability.short",
      required: false,
    },
    thursdayHours: {
      dataType: "DECIMAL",
      i18nKey: "calendar.shortday.thursday",
      required: false,
    },
    tuesdayHours: {
      dataType: "DECIMAL",
      i18nKey: "calendar.shortday.tuesday",
      required: false,
    },
    unassignedHours: {
      dataType: "DECIMAL",
      i18nKey: "hr.planning.unassignedHours",
      required: false,
    },
    wednesdayHours: {
      dataType: "DECIMAL",
      i18nKey: "calendar.shortday.wednesday",
      required: false,
    },
    weekendHours: {
      dataType: "DECIMAL",
      i18nKey: "hr.planning.weekend",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
