// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.KontoDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const KONTO_METADATA = {
  entity: "KontoDO",
  historizable: true,
  fields: {
    bezeichnung: {
      dataType: "STRING",
      i18nKey: "fibu.konto.bezeichnung",
      required: true,
      maxLength: 255,
    },
    city: {
      dataType: "STRING",
      i18nKey: "fibu.konto.city",
      required: false,
      maxLength: 100,
    },
    contactPerson: {
      dataType: "STRING",
      i18nKey: "fibu.konto.contactPerson",
      required: false,
      maxLength: 255,
    },
    country: {
      dataType: "STRING",
      i18nKey: "fibu.konto.country",
      required: false,
      maxLength: 2,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    eInvoiceEmail: {
      dataType: "STRING",
      i18nKey: "fibu.konto.eInvoiceEmail",
      required: false,
      maxLength: 255,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    leitwegId: {
      dataType: "STRING",
      i18nKey: "fibu.konto.leitwegId",
      required: false,
      maxLength: 50,
    },
    nummer: {
      dataType: "INT",
      i18nKey: "fibu.konto.nummer",
      required: true,
    },
    sellerBankAccountName: {
      dataType: "STRING",
      i18nKey: "fibu.konto.sellerBankAccountName",
      required: false,
      maxLength: 100,
    },
    status: {
      dataType: "STRING",
      i18nKey: "status",
      required: false,
      enumValues: [
        {
          value: "ACTIVE",
          i18nKey: "fibu.konto.status.active",
        },
        {
          value: "NONACTIVE",
          i18nKey: "fibu.konto.status.nonactive",
        },
      ],
    },
    street: {
      dataType: "STRING",
      i18nKey: "fibu.konto.street",
      required: false,
      maxLength: 255,
    },
    vatId: {
      dataType: "STRING",
      i18nKey: "fibu.konto.vatId",
      required: false,
      maxLength: 20,
    },
    zipCode: {
      dataType: "STRING",
      i18nKey: "fibu.konto.zipCode",
      required: false,
      maxLength: 10,
    },
  },
} as const satisfies EntityMetadata;
