// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.kost.KostZuweisungDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const KOST_ZUWEISUNG_METADATA = {
  entity: "KostZuweisungDO",
  historizable: true,
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    kost1: {
      dataType: "COST1",
      i18nKey: "fibu.kost1",
      required: false,
    },
    kost2: {
      dataType: "COST2",
      i18nKey: "fibu.kost2",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    netto: {
      dataType: "DECIMAL",
      i18nKey: "fibu.common.netto",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
