// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.kost.Kost2ArtDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const KOST2_ART_METADATA = {
  entity: "Kost2ArtDO",
  historizable: true,
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 5000,
    },
    fakturiert: {
      dataType: "BOOLEAN",
      i18nKey: "fibu.fakturiert",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "fibu.kost2art.nummer",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    name: {
      dataType: "STRING",
      i18nKey: "name",
      required: true,
      maxLength: 255,
    },
    projektStandard: {
      dataType: "BOOLEAN",
      i18nKey: "fibu.kost2art.projektStandard",
      required: false,
    },
    workFraction: {
      dataType: "DECIMAL",
      i18nKey: "fibu.kost2art.workFraction",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
