// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.kost.Kost2DO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const KOST2_METADATA = {
  entity: "Kost2DO",
  fields: {
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    formattedNumber: {
      dataType: "STRING",
      i18nKey: "fibu.kost2",
      required: false,
      readOnly: true,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    kostentraegerStatus: {
      dataType: "STRING",
      i18nKey: "status",
      required: false,
      enumValues: [
        {
          value: "ACTIVE",
          i18nKey: "fibu.kost.status.active",
        },
        {
          value: "NONACTIVE",
          i18nKey: "fibu.kost.status.nonactive",
        },
        {
          value: "ENDED",
          i18nKey: "fibu.kost.status.ended",
        },
      ],
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    workFraction: {
      dataType: "DECIMAL",
      i18nKey: "fibu.kost2.workFraction",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
