// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.kost.Kost1DO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const KOST1_METADATA = {
  entity: "Kost1DO",
  fields: {
    bereich: {
      dataType: "INT",
      i18nKey: "fibu.kost1.bereich",
      required: true,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    endziffer: {
      dataType: "INT",
      i18nKey: "fibu.kost1.endziffer",
      required: true,
    },
    formattedNumber: {
      dataType: "STRING",
      i18nKey: "fibu.kost1",
      required: false,
      readOnly: true,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    kostentraegerStatus: {
      dataType: "STRING",
      i18nKey: "status",
      required: false,
      enumValues: [
        {
          value: "ACTIVE",
          i18nKey: "fibu.kost.status.active",
        },
        {
          value: "NONACTIVE",
          i18nKey: "fibu.kost.status.nonactive",
        },
        {
          value: "ENDED",
          i18nKey: "fibu.kost.status.ended",
        },
      ],
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    nummernkreis: {
      dataType: "INT",
      i18nKey: "fibu.kost1.nummernkreis",
      required: true,
    },
    teilbereich: {
      dataType: "INT",
      i18nKey: "fibu.kost1.teilbereich",
      required: true,
    },
  },
} as const satisfies EntityMetadata;
