// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.KundeDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const KUNDE_METADATA = {
  entity: "KundeDO",
  historizable: true,
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    division: {
      dataType: "STRING",
      i18nKey: "fibu.kunde.division",
      required: false,
      maxLength: 255,
    },
    identifier: {
      dataType: "STRING",
      i18nKey: "fibu.kunde.identifier",
      required: false,
      maxLength: 20,
    },
    kost: {
      dataType: "STRING",
      i18nKey: "fibu.kunde.nummer",
      required: false,
      readOnly: true,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    name: {
      dataType: "STRING",
      i18nKey: "fibu.kunde.name",
      required: true,
      maxLength: 255,
    },
    nummer: {
      dataType: "LONG",
      i18nKey: "fibu.kunde.nummer",
      required: false,
    },
    status: {
      dataType: "STRING",
      i18nKey: "status",
      required: false,
      enumValues: [
        {
          value: "ACQUISISTION",
          i18nKey: "fibu.kunde.status.acquisition",
        },
        {
          value: "ACTIVE",
          i18nKey: "fibu.kunde.status.active",
        },
        {
          value: "NONACTIVE",
          i18nKey: "fibu.kunde.status.nonactive",
        },
        {
          value: "ENDED",
          i18nKey: "fibu.kunde.status.ended",
        },
        {
          value: "NONEXISTENT",
          i18nKey: "fibu.kunde.status.nonexistent",
        },
      ],
    },
  },
} as const satisfies EntityMetadata;
