// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.vacation.model.LeaveAccountEntryDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const LEAVE_ACCOUNT_ENTRY_METADATA = {
  entity: "LeaveAccountEntryDO",
  historizable: true,
  fields: {
    amount: {
      dataType: "DECIMAL",
      i18nKey: "vacation.leaveAccountEntry.amount",
      required: true,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    date: {
      dataType: "DATE",
      i18nKey: "date",
      required: true,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 255,
    },
    employee: {
      dataType: "EMPLOYEE",
      i18nKey: "fibu.employee",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    year: {
      dataType: "INT",
      i18nKey: "calendar.year",
      required: false,
      readOnly: true,
    },
  },
} as const satisfies EntityMetadata;
