// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.plugins.licensemanagement.LicenseDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const LICENSE_METADATA = {
  entity: "LicenseDO",
  historizable: true,
  fields: {
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    device: {
      dataType: "STRING",
      i18nKey: "plugins.licensemanagement.device",
      required: false,
      maxLength: 4000,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    key: {
      dataType: "STRING",
      i18nKey: "plugins.licensemanagement.key",
      required: false,
      maxLength: 10000,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    licenseHolder: {
      dataType: "STRING",
      i18nKey: "plugins.licensemanagement.licenseHolder",
      required: false,
      maxLength: 10000,
    },
    numberOfLicenses: {
      dataType: "INT",
      i18nKey: "plugins.licensemanagement.numberOfLicenses",
      required: false,
    },
    organization: {
      dataType: "STRING",
      i18nKey: "organization",
      required: false,
      maxLength: 1000,
    },
    ownerIds: {
      dataType: "STRING",
      i18nKey: "plugins.licensemanagement.owner",
      required: false,
      maxLength: 4000,
    },
    product: {
      dataType: "STRING",
      i18nKey: "plugins.licensemanagement.product",
      required: false,
      maxLength: 1000,
    },
    updateFromVersion: {
      dataType: "STRING",
      i18nKey: "plugins.licensemanagement.updateFromVersion",
      required: false,
      maxLength: 1000,
    },
    validSince: {
      dataType: "DATE",
      i18nKey: "plugins.licensemanagement.validSince",
      required: false,
    },
    validUntil: {
      dataType: "DATE",
      i18nKey: "plugins.licensemanagement.validUntil",
      required: false,
    },
    version: {
      dataType: "STRING",
      i18nKey: "plugins.licensemanagement.version",
      required: false,
      maxLength: 1000,
    },
  },
} as const satisfies EntityMetadata;
