// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.plugins.liquidityplanning.LiquiditySeriesDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const LIQUIDITY_SERIES_METADATA = {
  entity: "LiquiditySeriesDO",
  historizable: true,
  fields: {
    amount: {
      dataType: "DECIMAL",
      i18nKey: "fibu.common.betrag",
      required: false,
    },
    autoSetPaid: {
      dataType: "BOOLEAN",
      i18nKey: "plugins.liquidityplanning.entry.autoSetPaid",
      required: false,
    },
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    count: {
      dataType: "INT",
      i18nKey: "plugins.liquidityplanning.series.count",
      required: false,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    frequency: {
      dataType: "STRING",
      i18nKey: "common.recurrence.frequency.label",
      required: false,
      enumValues: [
        {
          value: "YEARLY",
          i18nKey: "common.recurrence.frequency.yearly",
        },
        {
          value: "MONTHLY",
          i18nKey: "common.recurrence.frequency.monthly",
        },
        {
          value: "WEEKLY",
          i18nKey: "common.recurrence.frequency.weekly",
        },
        {
          value: "DAILY",
          i18nKey: "common.recurrence.frequency.daily",
        },
        {
          value: "HOURLY",
          i18nKey: "common.recurrence.frequency.hourly",
        },
        {
          value: "NONE",
          i18nKey: "common.recurrence.frequency.none",
        },
      ],
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    intervalMonths: {
      dataType: "INT",
      i18nKey: "plugins.liquidityplanning.series.interval.months",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    startDate: {
      dataType: "DATE",
      i18nKey: "plugins.liquidityplanning.series.startDate",
      required: false,
    },
    subject: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.betreff",
      required: false,
      maxLength: 1000,
    },
  },
} as const satisfies EntityMetadata;
