// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.plugins.liquidityplanning.LiquidityEntryDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const LIQUIDITY_ENTRY_METADATA = {
  entity: "LiquidityEntryDO",
  historizable: true,
  fields: {
    amount: {
      dataType: "DECIMAL",
      i18nKey: "fibu.common.betrag",
      required: false,
    },
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    dateOfPayment: {
      dataType: "DATE",
      i18nKey: "plugins.liquidityplanning.entry.dateOfPayment",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    paid: {
      dataType: "BOOLEAN",
      i18nKey: "fibu.rechnung.status.bezahlt",
      required: false,
    },
    subject: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.betreff",
      required: false,
      maxLength: 1000,
    },
  },
} as const satisfies EntityMetadata;
