// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.plugins.memo.MemoDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const MEMO_METADATA = {
  entity: "MemoDO",
  historizable: false,
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    memo: {
      dataType: "STRING",
      i18nKey: "plugins.memo.memo",
      required: false,
      maxLength: 4000,
    },
    owner: {
      dataType: "USER",
      i18nKey: "plugins.memo.owner",
      required: false,
    },
    subject: {
      dataType: "STRING",
      i18nKey: "plugins.memo.subject",
      required: false,
      maxLength: 1000,
    },
  },
} as const satisfies EntityMetadata;
