// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.plugins.merlin.MerlinTemplateDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const MERLIN_TEMPLATE_METADATA = {
  entity: "MerlinTemplateDO",
  historizable: false,
  fields: {
    attachmentsLastUserAction: {
      dataType: "STRING",
      i18nKey: "attachment",
      required: false,
      maxLength: 10000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    dataTransferUsage: {
      dataType: "BOOLEAN",
      i18nKey: "plugins.merlin.template.dataTransferUsage",
      required: false,
      tooltipI18nKey: "plugins.merlin.template.dataTransferUsage.info",
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    fileNamePattern: {
      dataType: "STRING",
      i18nKey: "plugins.merlin.fileNamePattern",
      required: true,
      maxLength: 1000,
      tooltipI18nKey: "plugins.merlin.fileNamePattern.info",
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    name: {
      dataType: "STRING",
      i18nKey: "plugins.merlin.name",
      required: true,
      maxLength: 100,
    },
    pdfExport: {
      dataType: "BOOLEAN",
      i18nKey: "plugins.merlin.format.pdf",
      required: false,
      tooltipI18nKey: "plugins.merlin.format.pdf.info",
    },
    stronglyRestrictedFilenames: {
      dataType: "BOOLEAN",
      i18nKey: "plugins.merlin.forceStrictFilenames",
      required: false,
      tooltipI18nKey: "plugins.merlin.forceStrictFilenames.info",
    },
  },
} as const satisfies EntityMetadata;
