// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.notification.NotificationRuleDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const NOTIFICATION_RULE_METADATA = {
  entity: "NotificationRuleDO",
  historizable: true,
  fields: {
    active: {
      dataType: "BOOLEAN",
      i18nKey: "notification.rule.active",
      required: false,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    delivery: {
      dataType: "STRING",
      i18nKey: "notification.rule.delivery",
      required: false,
      maxLength: 4000,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    display: {
      dataType: "STRING",
      i18nKey: "notification.display",
      required: true,
      enumValues: [
        {
          value: "TOAST",
          i18nKey: "notification.displays.TOAST",
        },
        {
          value: "TOAST_CONFIRM",
          i18nKey: "notification.displays.TOAST_CONFIRM",
        },
        {
          value: "BANNER",
          i18nKey: "notification.displays.BANNER",
        },
      ],
    },
    editableByGroupIds: {
      dataType: "STRING",
      i18nKey: "notification.rule.editableByGroups",
      required: false,
      maxLength: 10000,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    manualDone: {
      dataType: "BOOLEAN",
      i18nKey: "notification.rule.manualDone",
      required: false,
    },
    menuBadge: {
      dataType: "STRING",
      i18nKey: "notification.rule.menuBadge",
      required: false,
      maxLength: 100,
    },
    name: {
      dataType: "STRING",
      i18nKey: "notification.rule.name",
      required: true,
      maxLength: 255,
    },
    params: {
      dataType: "STRING",
      i18nKey: "notification.rule.params",
      required: false,
      maxLength: 4000,
    },
    recipients: {
      dataType: "STRING",
      i18nKey: "notification.rule.recipients",
      required: false,
      maxLength: 10000,
    },
    ruleType: {
      dataType: "STRING",
      i18nKey: "notification.rule.ruleType",
      required: true,
      enumValues: [
        {
          value: "TIMESHEETS_MISSING",
          i18nKey: "notification.ruleTypes.TIMESHEETS_MISSING",
        },
        {
          value: "VACATION_LEFT",
          i18nKey: "notification.ruleTypes.VACATION_LEFT",
        },
        {
          value: "MANUAL",
          i18nKey: "notification.ruleTypes.MANUAL",
        },
      ],
    },
    schedule: {
      dataType: "STRING",
      i18nKey: "notification.rule.schedule",
      required: false,
      maxLength: 1000,
    },
    severity: {
      dataType: "STRING",
      i18nKey: "notification.severity",
      required: true,
      enumValues: [
        {
          value: "INFO",
          i18nKey: "notification.severities.INFO",
        },
        {
          value: "IMPORTANT",
          i18nKey: "notification.severities.IMPORTANT",
        },
        {
          value: "URGENT",
          i18nKey: "notification.severities.URGENT",
        },
      ],
    },
    subject: {
      dataType: "STRING",
      i18nKey: "notification.subject",
      required: false,
      maxLength: 1000,
    },
    text: {
      dataType: "STRING",
      i18nKey: "notification.text",
      required: false,
      maxLength: 100000,
    },
  },
} as const satisfies EntityMetadata;
