// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.PaymentScheduleDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const PAYMENT_SCHEDULE_METADATA = {
  entity: "PaymentScheduleDO",
  fields: {
    amount: {
      dataType: "DECIMAL",
      i18nKey: "fibu.common.betrag",
      required: false,
    },
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 255,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    reached: {
      dataType: "BOOLEAN",
      i18nKey: "fibu.common.reached",
      required: false,
    },
    scheduleDate: {
      dataType: "DATE",
      i18nKey: "fibu.rechnung.datum.short",
      required: false,
    },
    vollstaendigFakturiert: {
      dataType: "BOOLEAN",
      i18nKey: "fibu.auftrag.vollstaendigFakturiert",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
