// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.framework.persistence.user.entities.PFUserDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const PF_USER_METADATA = {
  entity: "PFUserDO",
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    dateFormat: {
      dataType: "STRING",
      i18nKey: "dateFormat",
      required: false,
      maxLength: 20,
    },
    deactivated: {
      dataType: "BOOLEAN",
      i18nKey: "user.deactivated",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 255,
    },
    email: {
      dataType: "STRING",
      i18nKey: "email",
      required: false,
      maxLength: 255,
    },
    excelDateFormat: {
      dataType: "STRING",
      i18nKey: "dateFormat.xls",
      required: false,
      maxLength: 20,
    },
    firstname: {
      dataType: "STRING",
      i18nKey: "firstName",
      required: false,
      maxLength: 255,
    },
    gender: {
      dataType: "STRING",
      i18nKey: "gender",
      required: false,
      enumValues: [
        {
          value: "MALE",
          i18nKey: "gender.male",
        },
        {
          value: "FEMALE",
          i18nKey: "gender.female",
        },
        {
          value: "DIVERSE",
          i18nKey: "gender.diverse",
        },
        {
          value: "UNKNOWN",
          i18nKey: "gender.unknown",
        },
      ],
    },
    gpgPublicKey: {
      dataType: "STRING",
      i18nKey: "user.gpgPublicKey",
      required: false,
      maxLength: 4096,
    },
    hrPlanning: {
      dataType: "BOOLEAN",
      i18nKey: "user.hrPlanningEnabled",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    jiraUsername: {
      dataType: "STRING",
      i18nKey: "user.jiraUsername",
      required: false,
      maxLength: 100,
      tooltipI18nKey: "user.jiraUsername.tooltip",
    },
    lastLogin: {
      dataType: "TIMESTAMP",
      i18nKey: "login.lastLogin",
      required: false,
    },
    lastPasswordChange: {
      dataType: "TIMESTAMP",
      i18nKey: "user.changePassword.password.lastChange",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    lastWlanPasswordChange: {
      dataType: "TIMESTAMP",
      i18nKey: "user.changeWlanPassword.lastChange",
      required: false,
    },
    lastname: {
      dataType: "STRING",
      i18nKey: "name",
      required: false,
      maxLength: 255,
    },
    ldapValues: {
      dataType: "STRING",
      i18nKey: "user.ldapValues",
      required: false,
      maxLength: 4000,
    },
    localUser: {
      dataType: "BOOLEAN",
      i18nKey: "user.localUser",
      required: false,
      tooltipI18nKey: "user.localUser.tooltip",
    },
    locale: {
      dataType: "LOCALE",
      i18nKey: "user.locale",
      required: false,
    },
    mobilePhone: {
      dataType: "STRING",
      i18nKey: "user.mobilePhone",
      required: false,
      maxLength: 255,
      tooltipI18nKey: "user.mobilePhone.info",
    },
    nickname: {
      dataType: "STRING",
      i18nKey: "nickname",
      required: false,
      maxLength: 255,
    },
    organization: {
      dataType: "STRING",
      i18nKey: "organization",
      required: false,
      maxLength: 255,
    },
    personalPhoneIdentifiers: {
      dataType: "STRING",
      i18nKey: "user.personalPhoneIdentifiers",
      required: false,
      maxLength: 255,
      tooltipI18nKey: "user.personalPhoneIdentifiers.tooltip.content",
    },
    restrictedUser: {
      dataType: "BOOLEAN",
      i18nKey: "user.restrictedUser",
      required: false,
      tooltipI18nKey: "user.restrictedUser.tooltip",
    },
    sshPublicKey: {
      dataType: "STRING",
      i18nKey: "user.sshPublicKey",
      required: false,
      maxLength: 4096,
    },
    timeNotation: {
      dataType: "STRING",
      i18nKey: "timeNotation",
      required: false,
      enumValues: [
        {
          value: "H12",
          i18nKey: "timeNotation.12",
        },
        {
          value: "H24",
          i18nKey: "timeNotation.24",
        },
      ],
    },
    timeZone: {
      dataType: "TIMEZONE",
      i18nKey: "timezone",
      required: false,
    },
    timeZoneString: {
      dataType: "STRING",
      i18nKey: "timezone",
      required: false,
      maxLength: 255,
    },
    username: {
      dataType: "STRING",
      i18nKey: "user.username",
      required: true,
      maxLength: 255,
    },
  },
} as const satisfies EntityMetadata;
