// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.poll.PollResponseDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const POLL_RESPONSE_METADATA = {
  entity: "PollResponseDO",
  historizable: true,
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    owner: {
      dataType: "USER",
      i18nKey: "poll.response.owner",
      required: false,
    },
    responses: {
      dataType: "STRING",
      i18nKey: "poll.responses",
      required: false,
      maxLength: 1000,
    },
  },
} as const satisfies EntityMetadata;
