// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.poll.PollDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const POLL_METADATA = {
  entity: "PollDO",
  historizable: true,
  fields: {
    attendeeIds: {
      dataType: "STRING",
      i18nKey: "poll.attendees",
      required: false,
      maxLength: 255,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deadline: {
      dataType: "DATE",
      i18nKey: "poll.deadline",
      required: true,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "poll.description",
      required: false,
      maxLength: 10000,
    },
    fullAccessGroupIds: {
      dataType: "STRING",
      i18nKey: "poll.full_access_groups",
      required: false,
      maxLength: 4000,
    },
    fullAccessUserIds: {
      dataType: "STRING",
      i18nKey: "poll.full_access_user",
      required: false,
      maxLength: 4000,
    },
    groupAttendeeIds: {
      dataType: "STRING",
      i18nKey: "poll.attendee_groups",
      required: false,
      maxLength: 255,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    inputFields: {
      dataType: "STRING",
      i18nKey: "poll.inputFields",
      required: false,
      maxLength: 1000,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    location: {
      dataType: "STRING",
      i18nKey: "poll.location",
      required: false,
      maxLength: 255,
    },
    owner: {
      dataType: "USER",
      i18nKey: "poll.owner",
      required: false,
    },
    state: {
      dataType: "STRING",
      i18nKey: "poll.state",
      required: true,
      enumValues: [
        {
          value: "RUNNING",
        },
        {
          value: "FINISHED",
        },
        {
          value: "FINISHED_AND_MAIL_SENT",
        },
      ],
    },
    title: {
      dataType: "STRING",
      i18nKey: "poll.title",
      required: true,
      maxLength: 1000,
    },
  },
} as const satisfies EntityMetadata;
