// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.orga.PostausgangDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const POSTAUSGANG_METADATA = {
  entity: "PostausgangDO",
  historizable: true,
  fields: {
    absender: {
      dataType: "STRING",
      i18nKey: "orga.posteingang.absender",
      required: false,
      maxLength: 1000,
    },
    bemerkung: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    datum: {
      dataType: "DATE",
      i18nKey: "date",
      required: true,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    empfaenger: {
      dataType: "STRING",
      i18nKey: "orga.postausgang.empfaenger",
      required: true,
      maxLength: 1000,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    inhalt: {
      dataType: "STRING",
      i18nKey: "orga.post.inhalt",
      required: true,
      maxLength: 1000,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    person: {
      dataType: "STRING",
      i18nKey: "orga.postausgang.person",
      required: false,
      maxLength: 1000,
    },
    type: {
      dataType: "STRING",
      i18nKey: "orga.post.type",
      required: true,
      enumValues: [
        {
          value: "BRIEF",
          i18nKey: "orga.post.type.brief",
        },
        {
          value: "PAECKCHEN",
          i18nKey: "orga.post.type.paeckchen",
        },
        {
          value: "PAKET",
          i18nKey: "orga.post.type.paket",
        },
        {
          value: "FAX",
          i18nKey: "orga.post.type.fax",
        },
        {
          value: "EINSCHREIBEN",
          i18nKey: "orga.post.type.einschreiben",
        },
        {
          value: "EINSCHREIBEN_MIT_RUECKSCHEIN",
          i18nKey: "orga.post.type.einschreibenMitRueckschein",
        },
        {
          value: "E_MAIL",
          i18nKey: "orga.post.type.e-mail",
        },
        {
          value: "LIEFERUNG",
          i18nKey: "orga.post.type.lieferung",
        },
      ],
    },
  },
} as const satisfies EntityMetadata;
