// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.ProjektDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const PROJEKT_METADATA = {
  entity: "ProjektDO",
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    headOfBusinessManager: {
      dataType: "USER",
      i18nKey: "fibu.headOfBusinessManager",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    identifier: {
      dataType: "STRING",
      i18nKey: "fibu.projekt.identifier",
      required: false,
      maxLength: 20,
    },
    internKost2_4: {
      dataType: "INT",
      i18nKey: "fibu.projekt.internKost2_4",
      required: false,
    },
    kost: {
      dataType: "STRING",
      i18nKey: "fibu.kost2",
      required: false,
      readOnly: true,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    name: {
      dataType: "STRING",
      i18nKey: "fibu.projekt.name",
      required: true,
      maxLength: 255,
    },
    nummer: {
      dataType: "INT",
      i18nKey: "fibu.projekt.nummer",
      required: true,
    },
    projectManager: {
      dataType: "USER",
      i18nKey: "fibu.projectManager",
      required: false,
    },
    projektManagerGroup: {
      dataType: "GROUP",
      i18nKey: "fibu.projekt.projektManagerGroup",
      required: false,
    },
    salesManager: {
      dataType: "USER",
      i18nKey: "fibu.salesManager",
      required: false,
    },
    status: {
      dataType: "STRING",
      i18nKey: "status",
      required: false,
      enumValues: [
        {
          value: "NONE",
          i18nKey: "fibu.projekt.status.none",
        },
        {
          value: "ACQUISISTION",
          i18nKey: "fibu.projekt.status.acquisition",
        },
        {
          value: "ON_HOLD",
          i18nKey: "fibu.projekt.status.onhold",
        },
        {
          value: "BUILD",
          i18nKey: "fibu.projekt.status.build",
        },
        {
          value: "PRODUCTIVE",
          i18nKey: "fibu.projekt.status.productive",
        },
        {
          value: "MAINTENANCE",
          i18nKey: "fibu.projekt.status.maintenance",
        },
        {
          value: "ENDED",
          i18nKey: "fibu.projekt.status.ended",
        },
      ],
    },
    task: {
      dataType: "TASK",
      i18nKey: "task",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
