// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.fibu.RechnungDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const RECHNUNG_METADATA = {
  entity: "RechnungDO",
  historizable: true,
  fields: {
    attachment: {
      dataType: "STRING",
      i18nKey: "fibu.attachment",
      required: false,
      maxLength: 255,
    },
    attachmentsLastUserAction: {
      dataType: "STRING",
      i18nKey: "attachment",
      required: false,
      maxLength: 10000,
    },
    bemerkung: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    besonderheiten: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.besonderheiten",
      required: false,
      maxLength: 4000,
    },
    betreff: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.betreff",
      required: false,
      maxLength: 4000,
    },
    bezahlDatum: {
      dataType: "DATE",
      i18nKey: "fibu.rechnung.bezahlDatum",
      required: false,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    currency: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.currency",
      required: false,
      maxLength: 10,
    },
    customerAddress: {
      dataType: "STRING",
      i18nKey: "fibu.konto.street",
      required: false,
      maxLength: 255,
    },
    customerCity: {
      dataType: "STRING",
      i18nKey: "fibu.konto.city",
      required: false,
      maxLength: 100,
    },
    customerContactPerson: {
      dataType: "STRING",
      i18nKey: "fibu.konto.contactPerson",
      required: false,
      maxLength: 255,
    },
    customerCountry: {
      dataType: "STRING",
      i18nKey: "fibu.konto.country",
      required: false,
      maxLength: 2,
    },
    customerEInvoiceEmail: {
      dataType: "STRING",
      i18nKey: "fibu.konto.eInvoiceEmail",
      required: false,
      maxLength: 255,
    },
    customerLeitwegId: {
      dataType: "STRING",
      i18nKey: "fibu.konto.leitwegId",
      required: false,
      maxLength: 50,
    },
    customerVatId: {
      dataType: "STRING",
      i18nKey: "fibu.konto.vatId",
      required: false,
      maxLength: 20,
    },
    customerZipCode: {
      dataType: "STRING",
      i18nKey: "fibu.konto.zipCode",
      required: false,
      maxLength: 10,
    },
    customerref1: {
      dataType: "STRING",
      i18nKey: "fibu.customerref1",
      required: false,
      maxLength: 255,
    },
    datum: {
      dataType: "DATE",
      i18nKey: "fibu.rechnung.datum",
      required: true,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    discountMaturity: {
      dataType: "DATE",
      i18nKey: "fibu.rechnung.discountMaturity",
      required: false,
    },
    discountPercent: {
      dataType: "DECIMAL",
      i18nKey: "fibu.rechnung.discountPercent",
      required: false,
    },
    discountZahlungsZielInTagen: {
      dataType: "INT",
      i18nKey: "fibu.rechnung.discountZahlungsZiel",
      required: false,
    },
    faelligkeit: {
      dataType: "DATE",
      i18nKey: "fibu.rechnung.faelligkeit",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    kundeText: {
      dataType: "STRING",
      i18nKey: "fibu.kunde.text",
      required: false,
      maxLength: 255,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    nummer: {
      dataType: "INT",
      i18nKey: "fibu.rechnung.nummer",
      required: false,
    },
    periodOfPerformanceBegin: {
      dataType: "DATE",
      i18nKey: "fibu.periodOfPerformance.from",
      required: false,
    },
    periodOfPerformanceEnd: {
      dataType: "DATE",
      i18nKey: "fibu.periodOfPerformance.to",
      required: false,
    },
    sellerBankAccount: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.sellerBankAccount",
      required: false,
      maxLength: 34,
    },
    status: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.status",
      required: false,
      enumValues: [
        {
          value: "GEPLANT",
          i18nKey: "fibu.rechnung.status.geplant",
        },
        {
          value: "GESTELLT",
          i18nKey: "fibu.rechnung.status.gestellt",
        },
        {
          value: "ZAHLUNGSERINNERUNG1",
          i18nKey: "fibu.rechnung.status.zahlungserinnerung1",
        },
        {
          value: "ZAHLUNGSERINNERUNG2",
          i18nKey: "fibu.rechnung.status.zahlungserinnerung2",
        },
        {
          value: "GEMAHNT",
          i18nKey: "fibu.rechnung.status.gemahnt",
        },
        {
          value: "STORNIERT",
          i18nKey: "fibu.rechnung.status.storniert",
        },
        {
          value: "BEZAHLT",
          i18nKey: "fibu.rechnung.status.bezahlt",
        },
      ],
    },
    typ: {
      dataType: "STRING",
      i18nKey: "fibu.rechnung.typ",
      required: false,
      enumValues: [
        {
          value: "RECHNUNG",
          i18nKey: "fibu.rechnung.typ.rechnung",
        },
        {
          value: "GUTSCHRIFTSANZEIGE_DURCH_KUNDEN",
          i18nKey: "fibu.rechnung.typ.gutschriftsAnzeigeDurchKunden",
        },
        {
          value: "CANCELLATION",
          i18nKey: "fibu.rechnung.typ.cancellation",
        },
      ],
    },
    year: {
      dataType: "INT",
      i18nKey: "calendar.year",
      required: false,
      readOnly: true,
    },
    zahlBetrag: {
      dataType: "DECIMAL",
      i18nKey: "fibu.rechnung.zahlBetrag",
      required: false,
    },
    zahlungsZielInTagen: {
      dataType: "INT",
      i18nKey: "fibu.rechnung.zahlungsZiel",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
