// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.vacation.model.RemainingLeaveDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const REMAINING_LEAVE_METADATA = {
  entity: "RemainingLeaveDO",
  fields: {
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    employee: {
      dataType: "EMPLOYEE",
      i18nKey: "vacation.employee",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    remainingFromPreviousYear: {
      dataType: "DECIMAL",
      i18nKey: "vacation.previousyearleave",
      required: false,
    },
    year: {
      dataType: "INT",
      i18nKey: "calendar.year",
      required: true,
    },
  },
} as const satisfies EntityMetadata;
