// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.scripting.ScriptDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const SCRIPT_METADATA = {
  entity: "ScriptDO",
  fields: {
    attachmentsLastUserAction: {
      dataType: "STRING",
      i18nKey: "attachment",
      required: false,
      maxLength: 10000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
      tooltipI18nKey: "scripting.script.description.tooltip",
    },
    executableByGroupIds: {
      dataType: "STRING",
      i18nKey: "scripting.script.executableByGroups",
      required: false,
      maxLength: 10000,
      tooltipI18nKey: "scripting.script.executableByGroups.info",
    },
    executableByUserIds: {
      dataType: "STRING",
      i18nKey: "scripting.script.executableByUsers",
      required: false,
      maxLength: 10000,
      tooltipI18nKey: "scripting.script.executableByUsers.info",
    },
    executeAsUser: {
      dataType: "USER",
      i18nKey: "scripting.script.executeAsUser",
      required: false,
      tooltipI18nKey: "scripting.script.executeAsUser.info",
    },
    filename: {
      dataType: "STRING",
      i18nKey: "file",
      required: false,
      maxLength: 255,
      tooltipI18nKey: "scripting.script.editForm.file.tooltip",
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    name: {
      dataType: "STRING",
      i18nKey: "scripting.script.name",
      required: true,
      maxLength: 255,
    },
    parameter1Description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    parameter1Name: {
      dataType: "STRING",
      i18nKey: "scripting.script.parameterName",
      required: false,
      maxLength: 100,
    },
    parameter1Type: {
      dataType: "STRING",
      i18nKey: "scripting.script.parameterType",
      required: false,
      enumValues: [
        {
          value: "INTEGER",
          i18nKey: "scripting.script.parameterType.integer",
        },
        {
          value: "DECIMAL",
          i18nKey: "scripting.script.parameterType.decimal",
        },
        {
          value: "STRING",
          i18nKey: "scripting.script.parameterType.string",
        },
        {
          value: "BOOLEAN",
          i18nKey: "scripting.script.parameterType.boolean",
        },
        {
          value: "DATE",
          i18nKey: "scripting.script.parameterType.date",
        },
        {
          value: "TIME_PERIOD",
          i18nKey: "scripting.script.parameterType.timePeriod",
        },
        {
          value: "TASK",
          i18nKey: "scripting.script.parameterType.task",
        },
        {
          value: "USER",
          i18nKey: "scripting.script.parameterType.user",
        },
      ],
    },
    parameter2Description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    parameter2Name: {
      dataType: "STRING",
      i18nKey: "scripting.script.parameterName",
      required: false,
      maxLength: 100,
    },
    parameter2Type: {
      dataType: "STRING",
      i18nKey: "scripting.script.parameterType",
      required: false,
      enumValues: [
        {
          value: "INTEGER",
          i18nKey: "scripting.script.parameterType.integer",
        },
        {
          value: "DECIMAL",
          i18nKey: "scripting.script.parameterType.decimal",
        },
        {
          value: "STRING",
          i18nKey: "scripting.script.parameterType.string",
        },
        {
          value: "BOOLEAN",
          i18nKey: "scripting.script.parameterType.boolean",
        },
        {
          value: "DATE",
          i18nKey: "scripting.script.parameterType.date",
        },
        {
          value: "TIME_PERIOD",
          i18nKey: "scripting.script.parameterType.timePeriod",
        },
        {
          value: "TASK",
          i18nKey: "scripting.script.parameterType.task",
        },
        {
          value: "USER",
          i18nKey: "scripting.script.parameterType.user",
        },
      ],
    },
    parameter3Description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    parameter3Name: {
      dataType: "STRING",
      i18nKey: "scripting.script.parameterName",
      required: false,
      maxLength: 100,
    },
    parameter3Type: {
      dataType: "STRING",
      i18nKey: "scripting.script.parameterType",
      required: false,
      enumValues: [
        {
          value: "INTEGER",
          i18nKey: "scripting.script.parameterType.integer",
        },
        {
          value: "DECIMAL",
          i18nKey: "scripting.script.parameterType.decimal",
        },
        {
          value: "STRING",
          i18nKey: "scripting.script.parameterType.string",
        },
        {
          value: "BOOLEAN",
          i18nKey: "scripting.script.parameterType.boolean",
        },
        {
          value: "DATE",
          i18nKey: "scripting.script.parameterType.date",
        },
        {
          value: "TIME_PERIOD",
          i18nKey: "scripting.script.parameterType.timePeriod",
        },
        {
          value: "TASK",
          i18nKey: "scripting.script.parameterType.task",
        },
        {
          value: "USER",
          i18nKey: "scripting.script.parameterType.user",
        },
      ],
    },
    parameter4Description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    parameter4Name: {
      dataType: "STRING",
      i18nKey: "scripting.script.parameterName",
      required: false,
      maxLength: 100,
    },
    parameter4Type: {
      dataType: "STRING",
      i18nKey: "scripting.script.parameterType",
      required: false,
      enumValues: [
        {
          value: "INTEGER",
          i18nKey: "scripting.script.parameterType.integer",
        },
        {
          value: "DECIMAL",
          i18nKey: "scripting.script.parameterType.decimal",
        },
        {
          value: "STRING",
          i18nKey: "scripting.script.parameterType.string",
        },
        {
          value: "BOOLEAN",
          i18nKey: "scripting.script.parameterType.boolean",
        },
        {
          value: "DATE",
          i18nKey: "scripting.script.parameterType.date",
        },
        {
          value: "TIME_PERIOD",
          i18nKey: "scripting.script.parameterType.timePeriod",
        },
        {
          value: "TASK",
          i18nKey: "scripting.script.parameterType.task",
        },
        {
          value: "USER",
          i18nKey: "scripting.script.parameterType.user",
        },
      ],
    },
    parameter5Description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    parameter5Name: {
      dataType: "STRING",
      i18nKey: "scripting.script.parameterName",
      required: false,
      maxLength: 100,
    },
    parameter5Type: {
      dataType: "STRING",
      i18nKey: "scripting.script.parameterType",
      required: false,
      enumValues: [
        {
          value: "INTEGER",
          i18nKey: "scripting.script.parameterType.integer",
        },
        {
          value: "DECIMAL",
          i18nKey: "scripting.script.parameterType.decimal",
        },
        {
          value: "STRING",
          i18nKey: "scripting.script.parameterType.string",
        },
        {
          value: "BOOLEAN",
          i18nKey: "scripting.script.parameterType.boolean",
        },
        {
          value: "DATE",
          i18nKey: "scripting.script.parameterType.date",
        },
        {
          value: "TIME_PERIOD",
          i18nKey: "scripting.script.parameterType.timePeriod",
        },
        {
          value: "TASK",
          i18nKey: "scripting.script.parameterType.task",
        },
        {
          value: "USER",
          i18nKey: "scripting.script.parameterType.user",
        },
      ],
    },
    parameter6Description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    parameter6Name: {
      dataType: "STRING",
      i18nKey: "scripting.script.parameterName",
      required: false,
      maxLength: 100,
    },
    parameter6Type: {
      dataType: "STRING",
      i18nKey: "scripting.script.parameterType",
      required: false,
      enumValues: [
        {
          value: "INTEGER",
          i18nKey: "scripting.script.parameterType.integer",
        },
        {
          value: "DECIMAL",
          i18nKey: "scripting.script.parameterType.decimal",
        },
        {
          value: "STRING",
          i18nKey: "scripting.script.parameterType.string",
        },
        {
          value: "BOOLEAN",
          i18nKey: "scripting.script.parameterType.boolean",
        },
        {
          value: "DATE",
          i18nKey: "scripting.script.parameterType.date",
        },
        {
          value: "TIME_PERIOD",
          i18nKey: "scripting.script.parameterType.timePeriod",
        },
        {
          value: "TASK",
          i18nKey: "scripting.script.parameterType.task",
        },
        {
          value: "USER",
          i18nKey: "scripting.script.parameterType.user",
        },
      ],
    },
    type: {
      dataType: "STRING",
      i18nKey: "scripting.script.type",
      required: false,
      enumValues: [
        {
          value: "KOTLIN",
        },
        {
          value: "GROOVY",
        },
        {
          value: "INCLUDE",
        },
      ],
    },
  },
} as const satisfies EntityMetadata;
