// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.plugins.skillmatrix.SkillEntryDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const SKILL_ENTRY_METADATA = {
  entity: "SkillEntryDO",
  historizable: false,
  fields: {
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    interest: {
      dataType: "INT",
      i18nKey: "plugins.skillmatrix.interest",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    owner: {
      dataType: "USER",
      i18nKey: "plugins.skillmatrix.owner",
      required: false,
    },
    rating: {
      dataType: "INT",
      i18nKey: "plugins.skillmatrix.rating",
      required: false,
    },
    skill: {
      dataType: "STRING",
      i18nKey: "plugins.skillmatrix.skill",
      required: true,
      maxLength: 255,
    },
  },
} as const satisfies EntityMetadata;
