// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.task.TaskDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const TASK_METADATA = {
  entity: "TaskDO",
  historizable: true,
  fields: {
    allowTimeOverlap: {
      dataType: "BOOLEAN",
      i18nKey: "task.allowTimeOverlap",
      required: false,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    duration: {
      dataType: "DECIMAL",
      i18nKey: "gantt.duration",
      required: false,
      min: 0,
      max: 10000,
    },
    endDate: {
      dataType: "DATE",
      i18nKey: "gantt.endDate",
      required: false,
    },
    ganttObjectType: {
      dataType: "STRING",
      i18nKey: "gantt.objectType",
      required: false,
      enumValues: [
        {
          value: "ACTIVITY",
          i18nKey: "gantt.objectType.activity",
        },
        {
          value: "SUMMARY",
          i18nKey: "gantt.objectType.summary",
        },
        {
          value: "MILESTONE",
          i18nKey: "gantt.objectType.milestone",
        },
      ],
    },
    ganttPredecessor: {
      dataType: "TASK",
      i18nKey: "gantt.predecessor",
      required: false,
    },
    ganttPredecessorOffset: {
      dataType: "INT",
      i18nKey: "gantt.predecessorOffset",
      required: false,
    },
    ganttRelationType: {
      dataType: "STRING",
      i18nKey: "gantt.relationType",
      required: false,
      enumValues: [
        {
          value: "START_START",
          i18nKey: "gantt.relationType.start_start",
        },
        {
          value: "START_FINISH",
          i18nKey: "gantt.relationType.start_finish",
        },
        {
          value: "FINISH_START",
          i18nKey: "gantt.relationType.finish_start",
        },
        {
          value: "FINISH_FINISH",
          i18nKey: "gantt.relationType.finish_finish",
        },
      ],
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    kost2BlackWhiteList: {
      dataType: "STRING",
      i18nKey: "fibu.kost2",
      required: false,
      maxLength: 1024,
    },
    kost2IsBlackList: {
      dataType: "BOOLEAN",
      i18nKey: "task.kost2list.type",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    maxHours: {
      dataType: "INT",
      i18nKey: "task.maxHours",
      required: false,
      min: 0,
      max: 9999,
    },
    parentTask: {
      dataType: "TASK",
      i18nKey: "task.parentTask",
      required: false,
    },
    priority: {
      dataType: "STRING",
      i18nKey: "priority",
      required: false,
      enumValues: [
        {
          value: "LEAST",
          i18nKey: "priority.least",
        },
        {
          value: "LOW",
          i18nKey: "priority.low",
        },
        {
          value: "MIDDLE",
          i18nKey: "priority.middle",
        },
        {
          value: "HIGH",
          i18nKey: "priority.high",
        },
        {
          value: "HIGHEST",
          i18nKey: "priority.highest",
        },
      ],
    },
    progress: {
      dataType: "INT",
      i18nKey: "task.progress",
      required: false,
      min: 0,
      max: 100,
    },
    protectTimesheetsUntil: {
      dataType: "DATE",
      i18nKey: "task.protectTimesheetsUntil",
      required: false,
    },
    protectionOfPrivacy: {
      dataType: "BOOLEAN",
      i18nKey: "task.protectionOfPrivacy",
      required: false,
    },
    reference: {
      dataType: "STRING",
      i18nKey: "task.reference",
      required: false,
      maxLength: 1000,
    },
    responsibleUser: {
      dataType: "USER",
      i18nKey: "task.assignedUser",
      required: false,
    },
    shortDescription: {
      dataType: "STRING",
      i18nKey: "shortDescription",
      required: false,
      maxLength: 255,
    },
    startDate: {
      dataType: "DATE",
      i18nKey: "gantt.startDate",
      required: false,
    },
    status: {
      dataType: "STRING",
      i18nKey: "status",
      required: false,
      enumValues: [
        {
          value: "N",
          i18nKey: "task.status.notOpened",
        },
        {
          value: "O",
          i18nKey: "task.status.opened",
        },
        {
          value: "C",
          i18nKey: "task.status.closed",
        },
      ],
    },
    timesheetBookingStatus: {
      dataType: "STRING",
      i18nKey: "task.timesheetBooking",
      required: true,
      enumValues: [
        {
          value: "INHERIT",
          i18nKey: "task.timesheetBooking.inherit",
        },
        {
          value: "OPENED",
          i18nKey: "task.timesheetBooking.opened",
        },
        {
          value: "ONLY_LEAFS",
          i18nKey: "task.timesheetBooking.onlyLeafs",
        },
        {
          value: "NO_BOOKING",
          i18nKey: "task.timesheetBooking.noBooking",
        },
        {
          value: "TREE_CLOSED",
          i18nKey: "task.timesheetBooking.treeClosed",
        },
      ],
    },
    title: {
      dataType: "STRING",
      i18nKey: "task.title",
      required: true,
      maxLength: 100,
    },
    workpackageCode: {
      dataType: "STRING",
      i18nKey: "task.workpackageCode",
      required: false,
      maxLength: 100,
    },
  },
} as const satisfies EntityMetadata;
