// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.teamcal.admin.model.TeamCalDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const TEAM_CAL_METADATA = {
  entity: "TeamCalDO",
  historizable: true,
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "plugins.teamcal.description",
      required: false,
      maxLength: 4000,
    },
    externalSubscription: {
      dataType: "BOOLEAN",
      i18nKey: "plugins.teamcal.externalsubscription.url",
      required: false,
    },
    externalSubscriptionUpdateInterval: {
      dataType: "INT",
      i18nKey: "plugins.teamcal.externalsubscription.updateInterval",
      required: false,
    },
    externalSubscriptionUrl: {
      dataType: "STRING",
      i18nKey: "plugins.teamcal.externalsubscription.label",
      required: false,
      maxLength: 255,
    },
    externalSubscriptionUrlAnonymized: {
      dataType: "STRING",
      i18nKey: "plugins.teamcal.externalsubscription.label",
      required: false,
      readOnly: true,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    includeLeaveDaysForGroups: {
      dataType: "STRING",
      i18nKey: "calendar.filter.vacation.groups",
      required: false,
      maxLength: 4000,
      tooltipI18nKey: "calendar.filter.vacation.groups.tooltip",
    },
    includeLeaveDaysForUsers: {
      dataType: "STRING",
      i18nKey: "calendar.filter.vacation.users",
      required: false,
      maxLength: 4000,
      tooltipI18nKey: "calendar.filter.vacation.users.tooltip",
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    owner: {
      dataType: "USER",
      i18nKey: "plugins.teamcal.owner",
      required: false,
    },
    title: {
      dataType: "STRING",
      i18nKey: "plugins.teamcal.title",
      required: false,
      maxLength: 1000,
    },
  },
} as const satisfies EntityMetadata;
