// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.teamcal.event.model.TeamEventDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const TEAM_EVENT_METADATA = {
  entity: "TeamEventDO",
  fields: {
    allDay: {
      dataType: "BOOLEAN",
      i18nKey: "plugins.teamcal.event.allDay",
      required: false,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    endDate: {
      dataType: "TIMESTAMP",
      i18nKey: "plugins.teamcal.event.endDate",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    location: {
      dataType: "STRING",
      i18nKey: "plugins.teamcal.event.location",
      required: false,
      maxLength: 1000,
    },
    note: {
      dataType: "STRING",
      i18nKey: "plugins.teamcal.event.note",
      required: false,
      maxLength: 4000,
    },
    startDate: {
      dataType: "TIMESTAMP",
      i18nKey: "plugins.teamcal.event.beginDate",
      required: false,
    },
    subject: {
      dataType: "STRING",
      i18nKey: "plugins.teamcal.event.subject",
      required: false,
      maxLength: 1000,
    },
  },
} as const satisfies EntityMetadata;
