// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.timesheet.TimesheetDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const TIMESHEET_METADATA = {
  entity: "TimesheetDO",
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "timesheet.description",
      required: false,
      maxLength: 4000,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    kost2: {
      dataType: "COST2",
      i18nKey: "fibu.kost2",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    location: {
      dataType: "STRING",
      i18nKey: "timesheet.location",
      required: false,
      maxLength: 100,
    },
    reference: {
      dataType: "STRING",
      i18nKey: "timesheet.reference",
      required: false,
      maxLength: 1000,
    },
    startTime: {
      dataType: "TIMESTAMP",
      i18nKey: "timesheet.startTime",
      required: true,
    },
    stopTime: {
      dataType: "TIMESTAMP",
      i18nKey: "timesheet.stopTime",
      required: true,
    },
    tag: {
      dataType: "STRING",
      i18nKey: "timesheet.tag",
      required: false,
      maxLength: 1000,
    },
    task: {
      dataType: "TASK",
      i18nKey: "task",
      required: false,
    },
    timeSavedByAI: {
      dataType: "DECIMAL",
      i18nKey: "timesheet.ai.timeSavedByAI",
      required: false,
      tooltipI18nKey: "timesheet.ai.timeSavedByAI.info",
    },
    timeSavedByAIDescription: {
      dataType: "STRING",
      i18nKey: "timesheet.ai.timeSavedByAIDescription",
      required: false,
      maxLength: 1000,
      tooltipI18nKey: "timesheet.ai.timeSavedByAIDescription.info",
    },
    timeSavedByAIUnit: {
      dataType: "STRING",
      i18nKey: "timesheet.ai.timeSavedByAIUnit",
      required: false,
      tooltipI18nKey: "timesheet.ai.timeSavedByAIUnit.info",
      enumValues: [
        {
          value: "PERCENTAGE",
          i18nKey: "percentage",
        },
        {
          value: "HOURS",
          i18nKey: "hours",
        },
      ],
    },
    user: {
      dataType: "USER",
      i18nKey: "user",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
