// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.plugins.todo.ToDoDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const TO_DO_METADATA = {
  entity: "ToDoDO",
  historizable: true,
  fields: {
    assignee: {
      dataType: "USER",
      i18nKey: "plugins.todo.assignee",
      required: false,
    },
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    description: {
      dataType: "STRING",
      i18nKey: "description",
      required: false,
      maxLength: 4000,
    },
    dueDate: {
      dataType: "DATE",
      i18nKey: "dueDate",
      required: false,
    },
    group: {
      dataType: "GROUP",
      i18nKey: "group",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    priority: {
      dataType: "STRING",
      i18nKey: "priority",
      required: false,
      enumValues: [
        {
          value: "LEAST",
          i18nKey: "priority.least",
        },
        {
          value: "LOW",
          i18nKey: "priority.low",
        },
        {
          value: "MIDDLE",
          i18nKey: "priority.middle",
        },
        {
          value: "HIGH",
          i18nKey: "priority.high",
        },
        {
          value: "HIGHEST",
          i18nKey: "priority.highest",
        },
      ],
    },
    reporter: {
      dataType: "USER",
      i18nKey: "plugins.todo.reporter",
      required: false,
    },
    resubmission: {
      dataType: "DATE",
      i18nKey: "resubmissionOnDate",
      required: false,
    },
    status: {
      dataType: "STRING",
      i18nKey: "plugins.todo.status",
      required: false,
      enumValues: [
        {
          value: "OPENED",
          i18nKey: "plugins.todo.status.opened",
        },
        {
          value: "IN_PROGRESS",
          i18nKey: "plugins.todo.status.inprogress",
        },
        {
          value: "RE_OPENED",
          i18nKey: "plugins.todo.status.reopened",
        },
        {
          value: "POSTPONED",
          i18nKey: "plugins.todo.status.postponed",
        },
        {
          value: "CLOSED",
          i18nKey: "plugins.todo.status.closed",
        },
      ],
    },
    subject: {
      dataType: "STRING",
      i18nKey: "plugins.todo.subject",
      required: false,
      maxLength: 1000,
    },
    task: {
      dataType: "TASK",
      i18nKey: "task",
      required: false,
    },
    type: {
      dataType: "STRING",
      i18nKey: "plugins.todo.type",
      required: false,
      enumValues: [
        {
          value: "TASK",
          i18nKey: "plugins.todo.type.task",
        },
        {
          value: "IMPROVEMENT",
          i18nKey: "plugins.todo.type.improvement",
        },
        {
          value: "REQUIREMENT",
          i18nKey: "plugins.todo.type.requirement",
        },
        {
          value: "HINT",
          i18nKey: "plugins.todo.type.hint",
        },
        {
          value: "BUG",
          i18nKey: "plugins.todo.type.bug",
        },
        {
          value: "WISH",
          i18nKey: "plugins.todo.type.wish",
        },
        {
          value: "IDEA",
          i18nKey: "plugins.todo.type.idea",
        },
      ],
    },
  },
} as const satisfies EntityMetadata;
