// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.framework.persistence.user.entities.UserAuthenticationsDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const USER_AUTHENTICATIONS_METADATA = {
  entity: "UserAuthenticationsDO",
  historizable: true,
  fields: {
    authenticatorToken: {
      dataType: "STRING",
      i18nKey: "user.authenticationToken.authenticator_key",
      required: false,
      maxLength: 100,
      tooltipI18nKey: "user.authenticationToken.authenticator_key.tooltip",
    },
    authenticatorTokenCreationDate: {
      dataType: "TIMESTAMP",
      i18nKey: "lastUpdate",
      required: false,
    },
    calendarExportToken: {
      dataType: "STRING",
      i18nKey: "user.authenticationToken.calendar_rest",
      required: false,
      maxLength: 100,
      tooltipI18nKey: "user.authenticationToken.calendar_rest.tooltip",
    },
    calendarExportTokenCreationDate: {
      dataType: "TIMESTAMP",
      i18nKey: "lastUpdate",
      required: false,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    davToken: {
      dataType: "STRING",
      i18nKey: "user.authenticationToken.dav_token",
      required: false,
      maxLength: 100,
      tooltipI18nKey: "user.authenticationToken.dav_token.tooltip",
    },
    davTokenCreationDate: {
      dataType: "TIMESTAMP",
      i18nKey: "lastUpdate",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    restClientToken: {
      dataType: "STRING",
      i18nKey: "user.authenticationToken.rest_client",
      required: false,
      maxLength: 100,
      tooltipI18nKey: "user.authenticationToken.rest_client.tooltip",
    },
    restClientTokenCreationDate: {
      dataType: "TIMESTAMP",
      i18nKey: "lastUpdate",
      required: false,
    },
    user: {
      dataType: "USER",
      i18nKey: "user",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
