// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.vacation.model.VacationDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const VACATION_METADATA = {
  entity: "VacationDO",
  fields: {
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    employee: {
      dataType: "EMPLOYEE",
      i18nKey: "vacation.employee",
      required: false,
    },
    endDate: {
      dataType: "DATE",
      i18nKey: "vacation.enddate",
      required: true,
    },
    halfDayBegin: {
      dataType: "BOOLEAN",
      i18nKey: "vacation.halfDayBegin",
      required: false,
      tooltipI18nKey: "vacation.halfDayBegin.tooltip",
    },
    halfDayEnd: {
      dataType: "BOOLEAN",
      i18nKey: "vacation.halfDayEnd",
      required: false,
      tooltipI18nKey: "vacation.halfDayEnd.tooltip",
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    manager: {
      dataType: "EMPLOYEE",
      i18nKey: "vacation.manager",
      required: false,
    },
    replacement: {
      dataType: "EMPLOYEE",
      i18nKey: "vacation.replacement",
      required: false,
    },
    special: {
      dataType: "BOOLEAN",
      i18nKey: "vacation.special",
      required: false,
      tooltipI18nKey: "vacation.special.tooltip",
    },
    startDate: {
      dataType: "DATE",
      i18nKey: "vacation.startdate",
      required: true,
    },
    status: {
      dataType: "STRING",
      i18nKey: "vacation.status",
      required: true,
      enumValues: [
        {
          value: "APPROVED",
          i18nKey: "vacation.status.approved",
        },
        {
          value: "REJECTED",
          i18nKey: "vacation.status.rejected",
        },
        {
          value: "IN_PROGRESS",
          i18nKey: "vacation.status.inProgress",
        },
      ],
    },
    vacationmode: {
      dataType: "STRING",
      i18nKey: "vacation.vacationmode",
      required: false,
      enumValues: [
        {
          value: "OWN",
          i18nKey: "vacation.own",
        },
        {
          value: "REPLACEMENT",
          i18nKey: "vacation.replacement",
        },
        {
          value: "MANAGER",
          i18nKey: "vacation.manager",
        },
        {
          value: "OTHER",
          i18nKey: "vacation.other",
        },
        {
          value: "HR",
          i18nKey: "vacation.hr",
        },
      ],
    },
  },
} as const satisfies EntityMetadata;
