// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.orga.VisitorbookEntryDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const VISITORBOOK_ENTRY_METADATA = {
  entity: "VisitorbookEntryDO",
  historizable: true,
  fields: {
    arrived: {
      dataType: "STRING",
      i18nKey: "orga.visitorbook.timeofvisit.arrive",
      required: false,
      maxLength: 100,
    },
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    dateOfVisit: {
      dataType: "DATE",
      i18nKey: "calendar.day",
      required: true,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    departed: {
      dataType: "STRING",
      i18nKey: "orga.visitorbook.timeofvisit.depart",
      required: false,
      maxLength: 100,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
  },
} as const satisfies EntityMetadata;
