// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.business.orga.VisitorbookDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const VISITORBOOK_METADATA = {
  entity: "VisitorbookDO",
  historizable: true,
  fields: {
    comment: {
      dataType: "STRING",
      i18nKey: "comment",
      required: false,
      maxLength: 4000,
    },
    company: {
      dataType: "STRING",
      i18nKey: "orga.visitorbook.company",
      required: false,
      maxLength: 255,
    },
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    deleted: {
      dataType: "BOOLEAN",
      i18nKey: "deleted",
      required: false,
    },
    firstname: {
      dataType: "STRING",
      i18nKey: "orga.visitorbook.firstname",
      required: true,
      maxLength: 30,
    },
    id: {
      dataType: "LONG",
      i18nKey: "id",
      required: false,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "modified",
      required: false,
    },
    lastname: {
      dataType: "STRING",
      i18nKey: "orga.visitorbook.lastname",
      required: true,
      maxLength: 30,
    },
    visitortype: {
      dataType: "STRING",
      i18nKey: "orga.visitorbook.visitortype",
      required: true,
      enumValues: [
        {
          value: "NORMAL",
          i18nKey: "orga.visitorbook.visitortype.normal",
        },
        {
          value: "EXTENDED",
          i18nKey: "orga.visitorbook.visitortype.extended",
        },
        {
          value: "FAMILY",
          i18nKey: "orga.visitorbook.visitortype.family",
        },
        {
          value: "SUPPLIER",
          i18nKey: "orga.visitorbook.visitortype.supplier",
        },
        {
          value: "WORKMAN",
          i18nKey: "orga.visitorbook.visitortype.workman",
        },
      ],
    },
  },
} as const satisfies EntityMetadata;
