// Generated by GenerateNextFieldMetadataMain (DevelopmentMainForRelease) — do not edit.
// Source of every rule: org.projectforge.security.webauthn.WebAuthnEntryDO (@PropertyInfo + JPA @Column),
// merged by ElementsRegistry.getElementInfo. Change the entity, then regenerate.

import type { EntityMetadata } from "./types";

export const WEB_AUTHN_ENTRY_METADATA = {
  entity: "WebAuthnEntryDO",
  fields: {
    created: {
      dataType: "TIMESTAMP",
      i18nKey: "created",
      required: false,
    },
    displayName: {
      dataType: "STRING",
      i18nKey: "webauthn.entry.displayName",
      required: false,
      maxLength: 1000,
    },
    lastUpdate: {
      dataType: "TIMESTAMP",
      i18nKey: "lastUpdate",
      required: false,
    },
    signCount: {
      dataType: "LONG",
      i18nKey: "webauthn.entry.signCount",
      required: false,
      tooltipI18nKey: "webauthn.entry.signCount.info",
    },
  },
} as const satisfies EntityMetadata;
