/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

tasks.withType<Test> {
    useJUnitPlatform()
    testLogging {
        events("PASSED", "FAILED", "SKIPPED", "STANDARD_OUT", "STANDARD_ERROR")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showStandardStreams = true
    }
}

dependencies {
    api(libs.org.springframework.boot.starter.logging)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.org.jetbrains.kotlin.kotlin.reflect)
    api(libs.org.apache.commons.commons.collections4)
    api(libs.org.apache.commons.commons.lang3)
    api(libs.commons.beanutils.commons.beanutils)
    api(libs.joda.time.joda.time)
    testImplementation(project(":projectforge-commons-test"))
    testApi(libs.org.junit.jupiter.api)
}

description = "projectforge-common"
