/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
}

dependencies {
    api(project(":projectforge-common"))
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.org.junit.jupiter.api)
}

description = "projectforge-commons-test"
