= ProjectForge - project management solution

ProjectForge is a web-based solution for project management including time tracking, team calendar, gantt-charting, financial administration, issue management,
controlling and managing work-break-down-structures (e. g. together with JIRA as issue management system).

Full documentation on: http://www.projectforge.org/pf-en/Documentation
Please visit: https://www.projectforge.org/documentation/developer-guide.html

== Quickstart from command line

[NOTE]
====
You only need the following steps for developing ProjectForge.
If you just want to run it, please download it from https://sourceforge.net/projects/pforge/
====

1. Checkout:  
   https://github.com/micromata/projectforge.git
2. Build ProjectForge:  
   `mvn clean install -DskipTests=true`
3. Run ProjectForge:
   `java -jar projectforge-application/target/projectforge-application-X.X.X.jar`
4. Open your browser:
   http://localhost:8080

=== Configuration of ProjectForge

.Minimal config `$HOME/ProjectForge/projectforge.properties`
----
projectforge.base.dir=${user.home}/ProjectForge
----

ProjectForge searches automatically for configurations in the following order:

1. Searches for `application-default.properties` in current directory.
2. Searches for `application.properties` in current directory.
3. Searches for `application-default.properties` in sub directory `config` of the current directory.
4. Searches for `application.properties` in sub directory `config` of the current directory.
5. Searches for `$HOME/ProjectForge/projectforge.properties`.

You may specify another config location: +
`java -jar target/projectforge-application-X.X.X.jar --spring.config.additional-location=file:/mypath/projectforge.properties`

=== Quickstart with Eclipse and maven

1. Launch eclipse
2. Import Maven project -> pom.xml in projectforge git root dir
3. Import Maven project -> pom.xml in projectforge-application dir
4. Start by simply running main (in `projectforge-application/src/main/java`): +
   `org.projectforge.start.ProjectForgeApplication.java`


Please note the detailed documentations for administrators, developers as well as for users.

Java version 8 is required since ProjectForge 6.0.
Please note, that Java version 8 is needed for developing and running ProjectForge.

=== Quickstart with IntelliJ

Start by simply running main (in `projectforge-application/src/main/java`): +
   `org.projectforge.start.ProjectForgeApplication.java`

== Adding your own plugins
ProjectForge support plugins. The existing menu can be modified and own entities and functionalities can be added.

The menu is customizable (you can add or remove menu entries in the config.xml file).
Deploy your plugins by adding your jar(s) to the plugin directory next to the jar file. In eclipse you have to add the plugin project to the run configuration classpath. The jars contains both, the Java classes and the web pages (Wicket-pages). Nothing more is needed.
Register your plugins in the administration menu at the web gui. You need to restart the server.
One advantage is that your own plugins are independent from new releases of the ProjectForge core system. In one of the next releases an example plugin will show you how easy it is to extend ProjectForge!

== Quickstart with PostgreSQL

=== Using PostgresSQL (Docker)

* Choose and set a database password: +
 `export PGPASSWORD=mypassword`
* Run PostgreSQL: +
`docker run --name projectforge-postgres -p 127.0.0.1:15432:5432 -e POSTGRES_PASSWORD=$PGPASSWORD -e POSTGRES_USER=projectforge -d postgres:11.2`
* Configure ProjectForge

.$HOME/ProjectForge/projectforge.properties
----
projectforge.base.dir=${user.home}/ProjectForge
spring.datasource.url=jdbc:postgresql://localhost:15432/projectforge
spring.datasource.username=projectforge
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
----

* Run ProjectForge and enjoy it.

.Some helpful docker commands
|===
|Stop|`docker stop projectforge-postgres`
|Start|`docker start projectforge-postgres`
|Import dump (optional)|`docker run -v ~/ProjectForgeBackup/pf.sql:/mnt/pf.sql -e PGPASSWORD=$PGPASSWORD -it --rm --link projectforge-postgres:postgres postgres:11.2 psql -h postgres -U projectforge -q -f /mnt/pf.sql  2>&1 > log.txt`
|Reset passwords (optional)|`update t_pf_user SET password='SHA{BC871652288E56E306CFA093BEFC3FFCD0ED8872}', password_salt=null, email='m.developer@acme.com';` +
password is now `test123`.
|PSQL|`docker run -e PGPASSWORD=$PGPASSWORD -it --rm --link projectforge-postgres:postgres postgres:11.2 psql -h postgres -U postgres`
|Uninstall|`docker rm projectforge-postgres`
|===


== Further configurations

Please have a lock at all available config parameters: https://github.com/micromata/projectforge/blob/develop/projectforge-application/src/main/resources/application.properties[application.properties]

== Building a new release

Draft (to be reviewed):

1. `mvn clean site` (Check test results and reports in all modules). If all tests are OK, continue with next step.
2. Tag a new release on GitHub.
3. Change version number of all `pom.xml` files: +
   `export PF_NEW_VERSION=6.26.0` +
   `find . -name pom.xml | xargs perl -pi -e 's|<version>.*</version><!-- projectforge.version -\->|<version>$ENV{PF_NEW_VERSION}</version><!-- projectforge.version -\->|g'`
4. Check git-modifications: all `pom.xml` files should have the new ProjectForge-Version.
5. `mvn clean install`
6. If all tests are finished successfully and the test of the ProjectForge-Application works for new and existing databases), proceeed:
7. Upload the jar to SourceForge.
8. Commit and publish the modified pom.xml files.
9. Create new SNAPSHOT-Release by increasing version number of all `pom.xml`files: +
   `export PF_NEW_VERSION=6.27.0-SNAPSHOT` +
   `find . -name pom.xml | xargs perl -pi -e 's|<version>.*</version><!-- projectforge.version -\->|<version>$ENV{PF_NEW_VERSION}</version><!-- projectforge.version -\->|g'`
10. Commit and publish the modified pom.xml files.
