==== Aktuell:
- Änderungskommentar bei Usern/Gruppen (JIRA-Nummern)
- AI timesavings: Zeit bei Eingabe ausrechnen, recent ai texte als vorlage.
- JCR: Tool for removing or recovering orphaned nodes.
- Favoriten bei Scriptausführung für Parameter.
- Viewpage für user für non-admins.
- Scripting: Ergebnis Unresolved reference 'memo', 'todo'.: line 94 to 94 (add only activated plugins)
- Can't get value type from 'org.projectforge.business.timesheet.TimesheetPrefData'. Class not found (old incompatible ProjectForge version)?
- Groovy-scripts: remove or fix.
- AG-Grid: setColumnStates wird nicht in den UserPrefs gespeichert.
- -XX:ReservedCodeCacheSize=100m
- QueryFilter.sortAndLimitMaxRowsWhileSelect: not yet supported
- Gradle-Version-Checker: Read lib.versions.toml und Vergleichen mit fatjar.
- Fehlerhinweis, wenn halber Tag für Urlaubsanfang/ende gewählt wird, es aber kein Arbeitstag ist.
- Kalendereinträge und Subscriptions.
- LoginProtection: Increases penalty time for DAV only after 5 tries.

- Admin für Datentransfer: show details of nodes, restore orphaned etc.
- Apple for Webauthn4j
- Abwesenheiten
- Fakturaquote Monatsbericht
- Google-Calendar-Integration

- Pagination of selects: Aktuell wird nicht DB-seitig paginiert, sondern immer die ganze Liste gefetched.
- remove all BaseDO.xxxId (lazy fetch) and replace callee by baseDO?.id
- Entitygraphen nutzen: ConflictVacationCache, AuftragCache etc.
  - AddressKampagnen: ebd. (massenhaft SQLs)

- Lazy-Breakpoint: AbstractLazyInitializer.initialize (#170)
org.hibernate.persister.entity.AbstractEntityPersister#generateSelectLazy:

History
- Suche:
- HistoryConvertContext: Am Ende alle displayProperties übernehmen.

- ProjektEdit: History enthält keine neuen Kost2DOs/Arten (Einträge sind aber da).
- CronReindexingHourlyJob ohne Effekt.
- Reindizierung der letzten n einträge nicht migriert (sinnvoll?).
- PFHistoryMasterDO: Indexe setzen, wenn Einträge wieder gehen.
- UserRightId: ClassBridge müsste eigentlich in die Felder der benutzenden DOs
- reindexing settings implementieren. Aktuell wird nur komplett gemass-indexed.
- History of AddressCampaignValueDO's (AddressCampaignValueDao.convertToDisplayHistoryEntries removed)

==== Später

- Fakturaquote
- Suche-Seite hat veraltete Bereiche, AddressListPage läuft auf Fehler.
- OrderExport: paymentSchedules werden gefetcht.

==== Ganz später

- Kalenderlist ruft x-fach DB: FIND GroupDO resultClass=GroupDO auf.

==== Rancher

[source]
----
docker system df
docker system prune -a --volumes
docker system df
docker volume ls
docker volume rm <volume-name>
----

==== Postgresql-Dump-Imports bechleunigen:

[source]
----
docker run --name projectforge-postgres -p 127.0.0.1:5432:5432 -e POSTGRES_PASSWORD=$PGPASSWORD -e POSTGRES_USER=projectforge -d postgres:13.18
docker run -e PGPASSWORD=$PGPASSWORD -it --rm --link projectforge-postgres:postgres postgres:13.18 psql -h postgres -U projectforge

ALTER SYSTEM SET fsync = off;
ALTER SYSTEM SET synchronous_commit = off;
SET maintenance_work_mem = '512MB';
----

==== Postgresql-Orderbook-Snapshots-Imports:

[source]
----
gunzip projectforge-*.sql.gz
docker run -v ~/ProjectForgeBackup/pf.sql:/mnt/pf.sql -e PGPASSWORD=$PGPASSWORD -it --rm --link projectforge-postgres:postgres postgres:13.18 psql -h postgres -U projectforge -q -f /mnt/pf.sql

drop view v_t_pf_user;
update t_pf_user_password SET password_hash='SHA{BC871652288E56E306CFA093BEFC3FFCD0ED8872}', password_salt=null;
update t_pf_user SET password='SHA{BC871652288E56E306CFA093BEFC3FFCD0ED8872}', password_salt=null, email='m.developer@localhost';
update t_calendar set ext_subscription=false;
insert into t_pf_user_password (pk,deleted,user_id,password_hash) values(2,false,2,'SHA{BC871652288E56E306CFA093BEFC3FFCD0ED8872}');
----

Orderbook-Export über die GUI Auftragsbuch -> Dev: export order book

[source]
----
\c postgres;
DROP DATABASE projectforge;
CREATE DATABASE projectforge;
----


Orderbooks importieren:
[source]
----
docker cp ~/ProjectForgeBackup/ProjectForge-Orderbook_*.gz projectforge-postgres:/tmp/

\set file_path '/tmp/ProjectForge-Orderbook_2023-11-01.gz'
INSERT INTO t_fibu_orderbook_snapshots (date, created, serialized_orderbook, size)  VALUES ('2023-11-01', NOW(), pg_read_binary_file(:'file_path')::bytea, (pg_stat_file(:'file_path')).size);

docker run -e PGPASSWORD=$PGPASSWORD -it --rm --link projectforge-postgres:postgres postgres:13.18 pg_dump -h postgres -U projectforge --data-only --column-inserts  --table=t_fibu_orderbook_snapshots
remove duplicates
psql -f export.sql
----
