-- Replacement of the JCR (Apache Oak): metadata of all attachments and their content (chunked). Own schema pf_files, so
-- the (large) files can be dumped separately: pg_dump -N pf_files ... (main dump), pg_dump -n pf_files -Fc ... (files).
-- No foreign keys to entity tables (as before with the JCR), so both dumps may be restored independently.
-- Same as the postgresql script (BLOB instead of BYTEA). Also used by the test cases for creating the schema.
-- Content of storage_type FS (e. g. DataTransfer) resides in the file system, only the metadata is stored here.
CREATE SCHEMA pf_files;

CREATE TABLE pf_files.t_attachment (
    pk               BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    file_id          CHARACTER VARYING(40)       NOT NULL,
    parent_path      CHARACTER VARYING(1000)     NOT NULL,
    rel_path         CHARACTER VARYING(255)      NOT NULL,
    file_name        CHARACTER VARYING(1000),
    description      CHARACTER VARYING(4000),
    file_size        BIGINT,
    stored_size      BIGINT,
    chunk_count      INTEGER                     NOT NULL,
    compression_type CHARACTER VARYING(10)       NOT NULL,
    storage_type     CHARACTER VARYING(10)       NOT NULL,
    checksum         CHARACTER VARYING(100),
    aes_encrypted    BOOLEAN                     NOT NULL,
    zip_mode         CHARACTER VARYING(30),
    created          TIMESTAMP                  ,
    created_by       CHARACTER VARYING(255),
    last_update      TIMESTAMP                  ,
    last_update_by   CHARACTER VARYING(255),
    CONSTRAINT unique_t_attachment_file_id UNIQUE (file_id)
);

CREATE INDEX idx_t_attachment_location
    ON pf_files.t_attachment (parent_path, rel_path);

CREATE TABLE pf_files.t_attachment_chunk (
    attachment_fk BIGINT  NOT NULL,
    seq           INTEGER NOT NULL,
    chunk_data    BLOB    NOT NULL,
    CONSTRAINT t_attachment_chunk_pkey PRIMARY KEY (attachment_fk, seq),
    CONSTRAINT t_attachment_chunk_attachment_fk FOREIGN KEY (attachment_fk)
        REFERENCES pf_files.t_attachment (pk) ON DELETE CASCADE
);

