package org.projectforge.ui

import com.google.gson.GsonBuilder
import org.junit.jupiter.api.Test

class UILayoutTest {
    @Test
    fun test() {
        var layout = UILayout.Builder().title("Edit book")
                .build()
                .add(UIElement(UIElementType.GROUP)
                        .add(UIElement.Builder(UIElementType.LABEL)
                                .forField("title")
                                .value("Title")
                                .build())
                        .add(UIElement.Builder(UIElementType.TEXT)
                                .id("title")
                                .required()
                                .maxLength(255)
                                .focus()
                                .build()))
                .add(UIElement(UIElementType.GROUP)
                        .add(UIElement.Builder(UIElementType.LABEL)
                                .forField("type")
                                .value("Type")
                                .build())
                        .add(UIElement.Builder(UIElementType.SELECT)
                                .id("type")
                                .build()
                                .add(UISelectValue("magazine", "Magazin"))
                                .add(UISelectValue("book", "Book")))
                        .add(UIElement.Builder(UIElementType.CHECKBOX)
                                .id("favorite")
                                .build()))
                .add(UIElement(UIElementType.GROUP)
                        .add(UIElement.Builder(UIElementType.LABEL)
                                .forField("authors")
                                .value("Authors")
                                .build())
                        .add(UIElement.Builder(UIElementType.TEXT)
                                .id("authors")
                                .maxLength(255)
                                .build()))
                .add(UIElement(UIElementType.ROW)
                        .add(UIElement.Builder(UIElementType.COL)
                                .length(6)
                                .build()
                                .add(UIElement(UIElementType.GROUP)
                                        .add(UIElement.Builder(UIElementType.LABEL)
                                                .forField("status")
                                                .value("Status")
                                                .build())
                                        .add(UIElement.Builder(UIElementType.SELECT)
                                                .id("status")
                                                .build()
                                                .add(UISelectValue("present", "vorhanden"))
                                                .add(UISelectValue("missed", "vermisst"))))
                                .add(UIElement(UIElementType.GROUP)
                                        .add(UIElement.Builder(UIElementType.LABEL)
                                                .forField("isbn")
                                                .value("ISBN")
                                                .build())
                                        .add(UIElement.Builder(UIElementType.TEXT)
                                                .id("isbn")
                                                .maxLength(255)
                                                .build())))
                        .add(UIElement.Builder(UIElementType.COL)
                                .length(6)
                                .build()
                                .add(UIElement(UIElementType.GROUP)
                                        .add(UIElement.Builder(UIElementType.LABEL)
                                                .forField("signature")
                                                .value("Signature")
                                                .build())
                                        .add(UIElement.Builder(UIElementType.TEXT)
                                                .id("signature")
                                                .maxLength(255)
                                                .build()))
                                .add(UIElement(UIElementType.GROUP)
                                        .add(UIElement.Builder(UIElementType.LABEL)
                                                .forField("keywords")
                                                .value("Keywords")
                                                .build())
                                        .add(UIElement.Builder(UIElementType.TEXT)
                                                .id("keywords")
                                                .maxLength(255)
                                                .build())))
                        .add(UIElement(UIElementType.GROUP)
                                .add(UIElement.Builder(UIElementType.LABEL)
                                        .forField("lendout")
                                        .value("Ausleihe")
                                        .build())
                                .add(UIElement.Builder(UIElementType.TEXT)
                                        .id("lendout")
                                        .maxLength(255)
                                        .build())))
        var gson = GsonBuilder().setPrettyPrinting().create()
        var jsonString = gson.toJson(layout)
        println(jsonString)
    }
}