---
layout: page
width: xsmall
title: About
permalink: /about/
---
:hide-uri-scheme:

ProjectForge® is a registered trademark. +
Copyright 2001-2021© Kai Reinhard. +
All rights reserved.

Kai Reinhard +
Micromata GmbH +
Marie-Calm-Str. 1-5 +
34131 Kassel +
Germany +
k.reinhard at micromata.com +

https://www.projectforge.org

Copyright 2001-2021© Kai Reinhard.All rights reserved.

ProjectForge® is a registered trademark of Kai Reinhard.

The contents published on the website are subject to copy right.All photographs are subjected to the right of use.The reproduction or redistribution of part or all texts or photographs is not allowed without written permission from the copyright holder.
Concept, design, structure and programming of the website are subjected to copy right law and as such may not be reprinted, reproduced or utilized in parts or in its entire form in any way without written permission from the copyright holder.
It is not permitted to alter or distribute the contents of this website.Nor is it allowed to copy or to duplicate any of these for commercial purposes.

Kai Reinhard cannot be held responsible for the contents of external websites to which links have been established.

== Team

[cols=3*,options=header]
|===
|Team
|Organization
|Role

| Kai Reinhard | Micromata GmbH | architect, developer
| Wolfgang Jung | Micromata GmbH | architect, developer
| Christian Claus | Micromata GmbH | developer
| Daniel Ludwig | Micromata GmbH | developer
| Roger Kommer | Micromata GmbH | developer
| Christian Tausendfreund | Micromata GmbH | developer
| Stefan Niemczyk | Micromata GmbH | developer
| Jan Brümmer | Micromata GmbH | developer
|===
