package org.projectforge.rest.ui

import org.projectforge.ui.*

class AddressLayout {
    companion object {
        fun createListLayout(): UILayout {
            return UILayout("Addressen")
                    .add(UITable("result-set")
                            .add(UITableColumn("lastUpdate", "geändert", dataType = UIDataType.DATE))
                            .add(UITableColumn("imageDataPreview", "Bild"))
                            .add(UITableColumn("name", "Name"))
                            .add(UITableColumn("firstName", "Vorname"))
                            .add(UITableColumn("organization", "Firma"))
                            .add(UITableColumn("email", "E-Mail"))
                            .add(UITableColumn("phoneNumbers", "Telefonnummern", dataType = UIDataType.CUSTOMIZED))
                            .add(UITableColumn("addressBooks", "Addressbücher")))
                    .addAction(UIButton("reset", "Rücksetzen", UIButtonStyle.DANGER))
                    .addAction(UIButton("search", "Suchen", UIButtonStyle.PRIMARY))
                    .add(UINamedContainer("filter-options")
                            .add(UIGroup()
                                    .add(UICheckbox("filter.filter", label = "Filter"))
                                    .add(UICheckbox("filter.newest", label = "die neuesten"))
                                    .add(UICheckbox("filter.favorites", label = "meine Favoriten"))
                                    .add(UICheckbox("filter.dublets", label = "Dupletten"))))
        }

        fun createEditLayout(): UILayout {
            return UILayout("Adresse bearbeiten")
                    .add(UIGroup()
                            .add(UILabel("Adressbücher", "addressbooks"))
                            .add(UIMultiSelect("addressbooks")))
                    .add(UIRow()
                            .add(UICol(6)
                                    .add(UIGroup()
                                            .add(UILabel("Name", "name"))
                                            .add(UIInput("name", 255, required = true, focus = true)))
                                    .add(UIGroup()
                                            .add(UILabel("Vorname", "firstName"))
                                            .add(UIInput("firstName", 255)))
                                    .add(UIGroup()
                                            .add(UILabel("Anrede", "gender"))
                                            .add(UISelect("gender")
                                                    .add(UISelectValue("male", "Herr"))
                                                    .add(UISelectValue("male", "Herr"))
                                                    .add(UISelectValue("divers", "divers"))
                                                    .add(UISelectValue("unkown", "unbekannt"))
                                                    .add(UISelectValue("company", "Firma"))))
                                    .add(UIGroup()
                                            .add(UILabel("Titel", "title"))
                                            .add(UIInput("title", 255))))
                            .add(UICol(6)
                                    .add(UIGroup()
                                            .add(UILabel("Kontaktstatus", "contactstatus"))
                                            .add(UISelect("gender")
                                                    .add(UISelectValue("active", "aktiv"))
                                                    .add(UISelectValue("inactive", "inaktiv"))))
                                    .add(UIGroup()
                                            .add(UILabel("Adressstatus", "addressstatus"))
                                            .add(UISelect("gender")
                                                    .add(UISelectValue("uptodate", "aktuell"))
                                                    .add(UISelectValue("outdated", "veraltet"))
                                                    .add(UISelectValue("leaved", "Unternehmen verlassen"))))
                                    .add(UIGroup()
                                            .add(UILabel("Firma", "company"))
                                            .add(UIInput("company", 255)))
                                    .add(UIGroup()
                                            .add(UILabel("Abteilung", "division"))
                                            .add(UIInput("division", 255)))
                                    .add(UIGroup()
                                            .add(UILabel("Position", "position"))
                                            .add(UIInput("position", 255)))))
                    .add(UIGroup()
                            .add(UILabel("Bemerkung", "comment"))
                            .add(UITextarea("comment", 4000)))
                    .addAction(UIButton("cancel", "Abbrechen", UIButtonStyle.DANGER))
                    .addAction(UIButton("markAsDeleted", "Als gelöscht markieren", UIButtonStyle.WARNING))
                    .addAction(UIButton("update", "Ändern", UIButtonStyle.PRIMARY))
        }
    }
}