package org.projectforge.rest.ui

import org.projectforge.ui.*

class BookLayout {
    companion object {
        fun createListLayout(): UILayout {
            return UILayout("Bücherliste")
                    .add(UITable("result-set")
                            .add(UITableColumn("created", "angelegt", dataType = UIDataType.DATE))
                            .add(UITableColumn("year", "Jahr"))
                            .add(UITableColumn("signature", "Signatur"))
                            .add(UITableColumn("authors", "Autoren"))
                            .add(UITableColumn("title", "Titel"))
                            .add(UITableColumn("keywords", "Schlüsselworte"))
                            .add(UITableColumn("lendOutBy", "Ausgeliehen von"))
                            .add(UITableColumn("year", "Jahr")))
                    .addAction(UIButton("reset", "Rücksetzen", UIButtonStyle.DANGER))
                    .addAction(UIButton("search", "Suchen", UIButtonStyle.PRIMARY))
                    .add(UINamedContainer("filter-options")
                            .add(UIGroup()
                                    .add(UICheckbox("filter.present", label = "vorhanden"))
                                    .add(UICheckbox("filter.missed", label = "vermisst"))
                                    .add(UICheckbox("filter.disposed", label = "entsorgt"))
                                    .add(UICheckbox("filter.onlyDeleted", label = "nur gelöscht"))
                                    .add(UICheckbox("filter.searchHistory", label = "Historie"))))
        }

        fun createEditLayout(): UILayout {
            return UILayout("Buch bearbeiten")
                    .add(UIGroup()
                            .add(UILabel("Titel", "title"))
                            .add(UIInput("title", 255, required = true, focus = true)))
                    .add(UIGroup()
                            .add(UILabel("Autoren", "authors"))
                            .add(UIInput("authors", 255)))
                    .add(UIRow()
                            .add(UICol(6)
                                    .add(UIGroup()
                                            .add(UILabel("Typ", "type"))
                                            .add(UISelect("type")
                                                    .add(UISelectValue("book", "Buch"))
                                                    .add(UISelectValue("magazine", "Magazin"))))
                                    .add(UIGroup()
                                            .add(UILabel("Veröffentlichungsjahr", "yearOfPublishing"))
                                            .add(UIInput("yearOfPublishing", 255)))
                                    .add(UIGroup()
                                            .add(UILabel("Status", "status"))
                                            .add(UISelect("status")
                                                    .add(UISelectValue("present", "vorhanden"))
                                                    .add(UISelectValue("missed", "vermisst"))))
                                    .add(UIGroup()
                                            .add(UILabel("Signatur", "signature"))
                                            .add(UIInput("signature", 255))))
                            .add(UICol(6)
                                    .add(UIGroup()
                                            .add(UILabel("ISBN", "isbn"))
                                            .add(UIInput("isbn", 255)))
                                    .add(UIGroup()
                                            .add(UILabel("Schlüsselwörter", "keywords"))
                                            .add(UIInput("keywords", 255)))
                                    .add(UIGroup()
                                            .add(UILabel("Verlag", "publisher"))
                                            .add(UIInput("publisher", 255)))
                                    .add(UIGroup()
                                            .add(UILabel("Herausgeber", "editor"))
                                            .add(UIInput("editor", 255)))))
                    .add(UIGroup()
                            .add(UILabel("Ausleihe"))
                            .add(UICustomized("lendOut")
                                    .add("lendOutBy", "kai")))
                    .add(UIGroup()
                            .add(UILabel("Ausleihnotiz (optional)", "lendOutRemark"))
                            .add(UITextarea("lendOutRemark", 4000)))
                    .add(UIGroup()
                            .add(UILabel("Zusammenfassung", "abstract"))
                            .add(UITextarea("abstact", 4000)))
                    .add(UIGroup()
                            .add(UILabel("Bemerkung", "comment"))
                            .add(UITextarea("comment", 4000)))
                    .addAction(UIButton("cancel", "Abbrechen", UIButtonStyle.DANGER))
                    .addAction(UIButton("markAsDeleted", "Als gelöscht markieren", UIButtonStyle.WARNING))
                    .addAction(UIButton("update", "Ändern", UIButtonStyle.PRIMARY))
        }
    }
}