CREATE TABLE t_address (
  pk                     INTEGER               NOT NULL,
  created                TIMESTAMP WITHOUT TIME ZONE,
  deleted                BOOLEAN               NOT NULL,
  last_update            TIMESTAMP WITHOUT TIME ZONE,
  address_status         CHARACTER VARYING(20) NOT NULL,
  addresstext            CHARACTER VARYING(255),
  birthday               DATE,
  business_phone         CHARACTER VARYING(255),
  city                   CHARACTER VARYING(255),
  comment                CHARACTER VARYING(5000),
  communication_language CHARACTER VARYING(255),
  contact_status         CHARACTER VARYING(20) NOT NULL,
  country                CHARACTER VARYING(255),
  division               CHARACTER VARYING(255),
  email                  CHARACTER VARYING(255),
  fax                    CHARACTER VARYING(255),
  fingerprint            CHARACTER VARYING(255),
  first_name             CHARACTER VARYING(255),
  form                   CHARACTER VARYING(10),
  mobile_phone           CHARACTER VARYING(255),
  name                   CHARACTER VARYING(255),
  organization           CHARACTER VARYING(255),
  positiontext           CHARACTER VARYING(255),
  postal_addresstext     CHARACTER VARYING(255),
  postal_city            CHARACTER VARYING(255),
  postal_country         CHARACTER VARYING(255),
  postal_state           CHARACTER VARYING(255),
  postal_zip_code        CHARACTER VARYING(255),
  private_addresstext    CHARACTER VARYING(255),
  private_city           CHARACTER VARYING(255),
  private_country        CHARACTER VARYING(255),
  private_email          CHARACTER VARYING(255),
  private_mobile_phone   CHARACTER VARYING(255),
  private_phone          CHARACTER VARYING(255),
  private_state          CHARACTER VARYING(255),
  private_zip_code       CHARACTER VARYING(255),
  public_key             CHARACTER VARYING(20000),
  state                  CHARACTER VARYING(255),
  title                  CHARACTER VARYING(255),
  website                CHARACTER VARYING(255),
  zip_code               CHARACTER VARYING(255),
  tenant_id              INTEGER,
  imagedata              BYTEA,
  image_data_preview     BYTEA,
  uid                    CHARACTER VARYING(255)
);

CREATE TABLE t_plugin_calendar (
  pk                               INTEGER               NOT NULL,
  created                          TIMESTAMP WITHOUT TIME ZONE,
  deleted                          BOOLEAN               NOT NULL,
  last_update                      TIMESTAMP WITHOUT TIME ZONE,
  description                      CHARACTER VARYING(4000),
  ext_subscription                 BOOLEAN DEFAULT FALSE NOT NULL,
  ext_subscription_calendar_binary BYTEA,
  ext_subscription_hash            CHARACTER VARYING(255),
  ext_subscription_update_interval INTEGER,
  ext_subscription_url             CHARACTER VARYING(255),
  full_access_group_ids            CHARACTER VARYING(255),
  full_access_user_ids             CHARACTER VARYING(255),
  minimal_access_group_ids         CHARACTER VARYING(255),
  minimal_access_user_ids          CHARACTER VARYING(255),
  readonly_access_group_ids        CHARACTER VARYING(255),
  readonly_access_user_ids         CHARACTER VARYING(255),
  title                            CHARACTER VARYING(1000),
  tenant_id                        INTEGER,
  owner_fk                         INTEGER
);

CREATE TABLE t_plugin_calendar_event_attachment (
  pk             INTEGER NOT NULL,
  created        TIMESTAMP WITHOUT TIME ZONE,
  deleted        BOOLEAN NOT NULL,
  last_update    TIMESTAMP WITHOUT TIME ZONE,
  content        BYTEA,
  filename       CHARACTER VARYING(255),
  tenant_id      INTEGER,
  team_event_fk2 INTEGER
);

CREATE TABLE t_plugin_lm_license (
  pk                  INTEGER NOT NULL,
  created             TIMESTAMP WITHOUT TIME ZONE,
  deleted             BOOLEAN NOT NULL,
  last_update         TIMESTAMP WITHOUT TIME ZONE,
  comment             CHARACTER VARYING(4000),
  device              CHARACTER VARYING(4000),
  file1               BYTEA,
  file2               BYTEA,
  file_name1          CHARACTER VARYING(255),
  file_name2          CHARACTER VARYING(255),
  key                 CHARACTER VARYING(10000),
  license_holder      CHARACTER VARYING(10000),
  number_of_licenses  INTEGER,
  organization        CHARACTER VARYING(1000),
  ownerids            CHARACTER VARYING(4000),
  product             CHARACTER VARYING(1000),
  status              CHARACTER VARYING(20),
  update_from_version CHARACTER VARYING(1000),
  valid_since         DATE,
  valid_until         DATE,
  version             CHARACTER VARYING(1000),
  tenant_id           INTEGER
);

CREATE TABLE t_script (
  pk             INTEGER                NOT NULL,
  created        TIMESTAMP WITHOUT TIME ZONE,
  deleted        BOOLEAN                NOT NULL,
  last_update    TIMESTAMP WITHOUT TIME ZONE,
  description    CHARACTER VARYING(4000),
  file           BYTEA,
  file_name      CHARACTER VARYING(255),
  name           CHARACTER VARYING(255) NOT NULL,
  parameter1name CHARACTER VARYING(100),
  parameter1type CHARACTER VARYING(20),
  parameter2name CHARACTER VARYING(100),
  parameter2type CHARACTER VARYING(20),
  parameter3name CHARACTER VARYING(100),
  parameter3type CHARACTER VARYING(20),
  parameter4name CHARACTER VARYING(100),
  parameter4type CHARACTER VARYING(20),
  parameter5name CHARACTER VARYING(100),
  parameter5type CHARACTER VARYING(20),
  parameter6name CHARACTER VARYING(100),
  parameter6type CHARACTER VARYING(20),
  script         BYTEA,
  script_backup  BYTEA,
  tenant_id      INTEGER
);