package org.projectforge

import java.io.File
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter

/**
 * Generates a properties file containing git information as well as gradle information such as version and build date.
 */
class BuildPropertiesGenerator(
    private val rootDirPath: String,
    private val outputFilePath: String,
    private val projectVersion: String
) {
    fun generate() {
        val rootDir = File(rootDirPath)
        val outputFile = File(outputFilePath)

        val branch = "git rev-parse --abbrev-ref HEAD".runCommand(rootDir) ?: "unknown"
        val commitIdFull = "git rev-parse HEAD".runCommand(rootDir) ?: "unknown"
        val commitIdAbbrev = commitIdFull.take(7)
        val commitTime = "git show -s --format=%ci HEAD".runCommand(rootDir) ?: "unknown"
        val isDirty = "git status --porcelain".runCommand(rootDir)?.isNotBlank().toString()
        val now = OffsetDateTime.now(ZoneOffset.UTC)
        val buildDate = now.format(DateTimeFormatter.ISO_OFFSET_DATE)
        val buildTimeStamp = now.format(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss'Z'"))

        outputFile.parentFile.mkdirs()
        outputFile.writeText(
            """
            # Generated by Gradle
            gradle.version=$projectVersion
            gradle.build.date=$buildDate
            gradle.build.timestamp=$buildTimeStamp
            git.branch=$branch
            git.commit.id.abbrev=$commitIdAbbrev
            git.commit.id.full=$commitIdFull
            git.commit.time=$commitTime
            git.dirty=$isDirty
            """.trimIndent()
        )
        println("Git properties written to ${outputFile.absolutePath}")
    }

    private fun String.runCommand(workingDir: File): String? {
        return try {
            val process = ProcessBuilder(*split(" ").toTypedArray())
                .directory(workingDir)
                .redirectErrorStream(true)
                .start()
            process.inputStream.bufferedReader().readText().trim().takeIf { process.waitFor() == 0 }
        } catch (e: Exception) {
            null
        }
    }
}
