FROM ubuntu:latest

ADD ssh /root/.ssh

# Let's start with some basic stuff.
RUN apt-get update -qq && apt-get install -qqy \
    apt-transport-https \
    ca-certificates \
    curl \
    lxc \
    iptables

# Install Docker from Docker Inc. repositories.
RUN curl -sSL https://get.docker.com/ | sh

# Install the magic wrapper.
ADD ./wrapdocker /usr/local/bin/wrapdocker
RUN chmod +x /usr/local/bin/wrapdocker

# Define additional metadata for our image.
VOLUME /var/lib/docker
CMD ["wrapdocker"]

EXPOSE 8080

# for jenkins
RUN wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -
RUN echo deb https://pkg.jenkins.io/debian-stable binary/ >> /etc/apt/sources.list
RUN apt-get update -qq && apt-get install -qqy jenkins

# default jenkins home directory
ENV JENKINS_HOME /var/jenkins

# default command to launch jenkins
CMD java -jar /usr/share/jenkins/jenkins.war