= ProjectForge development documentation
Micromata GmbH, Version {version}
:toc:
:toclevels: 4

:last-update-label: Copyright (C) 2024, Last updated

ifdef::env-github,env-browser[:outfilesuffix: .adoc]
link:index{outfilesuffix}[Top]

:sectnums:

== How to deploy a new release?

1. Modify `site/_changelogs` with updated release information
2. Run `DevelopmentMainForRelease.kt` main to sort all i18n resources and fix source file headers, if any.
3. Define new release variable: +
   `./build.gradle.kts: version = '8.0'`
4. `./gradlew clean build`
5. If all tests are finished successfully and the test of the ProjectForge-Application works for new and existing databases), proceeed:
6. Copy executable jar file from `projectforge-application/build/libs/projectforge-application-\*.jar` to SourceForge and tag this file as default for all platforms
7. Building and pushing docker
    a. `cp projectforge-application/build/libs/projectforge-application*.jar .`
    b. `docker build -t micromata/projectforge:latest .`
    c. `docker tag bc0459ed7d01 micromata/projectforge:$PF_NEW_VERSION` (use image id for tagging)
    d. `docker push micromata/projectforge:$PF_NEW_VERSION`
    e. `docker push micromata/projectforge:latest`
8. Merge the release branch into the master and develop branch (Git Flow: Finish release)
9. Tag master branch with version number
10. Change to develop branch
11. Create new SNAPSHOT-Release by increasing version number: +
`./build.gradle.kts: version = '8.0.1-SNAPSHOT'`
12. Commit everything to master and develop branch and push it to Github
13. Upload the saved jar files to Github (Create release from taged version) and SourceForge (e.g. as zip (see previous versions as example)).
