ProjectForge development documentation
=======================================
Micromata GmbH, Version {version}
:toc:
:toclevels: 4

:last-update-label: Copyright (C) 2019, Last updated

ifdef::env-github,env-browser[:outfilesuffix: .adoc]
link:index{outfilesuffix}[Top]

:sectnums:

== Architecture

=== The layers

The main functionality of ProjectForge is to display and search data list and to modify data (CRUD - create, read, update and delete). Therefore the
goal of the architecture is not to write thousands lines of code for same base functionality.

==== Business layer (business)

The business layer handles all entities including access checking for CRUD operations as well as well as user services (storage for preferences etc.).


==== REST API and front-end support (rest)

The REST layer provides CRUD services etc. and also front-end support functionality. These both parts might be separated, but regarding code efficiency both are combined.
For using only CRUD operations (without interest in the front-end support functionality), so simply ignore some additional information in the result data (json).

==== ReactJS (webapp)

The ReactJS layer handles the data and UI layout information provided by the REST API. A dynamic layout management system is used to visualize the
html pages defined by the server. In addition customized components are provided for specialized functionality.

Except for the customized components and pages, the client has no clue, of what entities are provided by the server. The client gets the menu from the server and
calls the server for how to proceed for given entities (e. g. list or edit view of users, addresses, book, time sheets etc.). The server provides both, the data
to display (model) and the layout information of how to display (view).
The users actions (clicking on buttons or menu entries) results in most cases in server calls, and the server responses how to proceed:

1. The front-end supports defined state manipulations by the server (see below, e. g. selecting favorite filter etc., or list of calendar events after selecting calendars etc.)
2. The server may respond in addition on URLs to redirect to by the front-end.
3. The server provides also validation information (e. g. max-length of text input fields) as well as errors after complex server-side validations after submitting a form.
4. The front-end defines customized pages and components (non standard components are not ruled by the server). Examples: Image upload for addresses or lend-out functionality for books.


== Backend

Java is the language used since the very beginning of ProjectForge in 2001.

With ProjectForge 7.x Kotlin and ReactJS is introduced.

=== Why Kotlin in addition to Java?
* Kotlin is used for smarter and less code, especially for BaseDO objects as well as for easier creation of data transfer classes for the new introduced REST API.
* Other advantages:
  ** Smart operations on collections (map, find, sort etc.)
  ** Immutable objects, classes and functions as default.
  ** Null safety
  ** Compability with JAVA code.
* Java and Kotlin will both exist. Only most BaseDO classes were migrated and new functionality will mostly be written in Kotlin.

Please note: Kotlin must be compiled with target 1.8 (Java version) but is fully runnable on Java 9, 10 and 11 VMs.

==== Base entities (BaseDO)
The BaseDO objects are the entities of ProjectForge stored in the data base. As default, all modification of entity attributes are available in a history with the information about the modification (user, timestamp, old and new value).

.AddressDO.kt
[#src-listing]
[source,java]
----
class AddressDO : DefaultBaseWithAttrDO<AddressDO>() {

    @PropertyInfo(i18nKey = "address.contactStatus")
    @Field
    var contactStatus = ContactStatus.ACTIVE

    @PropertyInfo(i18nKey = "name", required = true)
    @Field
    @get:Column(length = 255)
    var name: String? = null

    @PropertyInfo(i18nKey = "address.phone", additionalI18nKey = "address.business")
    @Field
    @get:Column(length = 255)
    var businessPhone: String? = null
    ...
}

----

As example some parts of `AddressDO.kt` are shown and described below:

|===
|`@PropertyInfo` | The given `i18nKey` is used for translating the field label and will be served for the frontend(s).
The optional given `additionalI18nKey` is used for having an additional translated label, in the example there are different phone numbers, categorized as business or private.
|`@Field`|This database field will be indexed and available for a full text search as well as for specifying search values for this field by the user.
|`@get:Column(length=255)` | JPA annotations. The JPA annotations are available as Meta information from all parts and will be served for the frontends, e. g. for
defining the html field `max-length` of input fields.
|Property type|The property type is also available as Meta information also for the clients. The input fields of the frontend may be autodetected (string, date picker, user selectors, drop down choices for enums etc.)
|===

.ContactStatus.java
[#src-listing]
[source,java]
----
public enum ContactStatus implements I18nEnum
{
  ACTIVE("active"), NON_ACTIVE("nonActive"), DEPARTED("departed");

  public String getI18nKey()
  {
    return "address.contactStatus." + key;
  }
  ...
}
----
The enumerations of type `I18nEnum` are also designed for auto translation purposes. The field `contactStatus` will be presented as a drop down choice field with translated
labels.

==== BaseDao
The BaseDao classes provide all CRUD operations for the BaseDO entities and will handle the access rights. No user is able to select or modify entities without the required access rights.

The implementation of BaseDao for entities, such as users, addresses, books etc. extends the BaseDao object by defining the access rights and additional special functionality. The base CRUD functionality including access
checks, history service etc. will be inherited.

== REST API

Since version 7.0 ProjectForge provides all CRUD operations through a REST API and much more. The user's access rights will be checked. For available standard REST calls you
may refer the REST calls described in the UI section below.

== UI
The new UI is based on REST and ReactJS. The ReactJS code includes a dynamic auto layout component for standard components, such as:

|===
|Input | Html input fields (text, date picker with text input etc.)
|Select boxes | For selecting values for e. g. enums (auto completion and asynchronous are calls supported.)
|Multi select | Select field for selecting multi values (auto completion, asynchronous). This may be used for selecting values as well as of selecting entities assigned to current object, e. g. users may assigned to groups or calendars are selectable for displaying.
|Fieldset|Fieldsets with titles and length settings (Bootstrap grid system is supported)
|Columns|Columns with length settings (Bootstrap grid system is supported)
|Tables|For displaying result sets etc.
|Customized fields|You may register customized UI components which will be used for displaying and modifiing values. Refer the image upload for addresses as an example.
|...|...
|===

=== Responsive
Bootstrap is used and responsive layout control is fully supported.

=== Standard list views

Available REST calls:

[cols=3*,options="header"]
|===
|Rest call|Description|Return values

|`rs/address/initialList`
|Initial call for displaying a list including layout and filter
a|* UI layout (available filter options, columns of the result data, page menu items, ...)
* recent used filter by the user
* Available favorites
* Result set

|`rs/address/list`
|Call with current filter settings as POST parameter after clicking the search button.
a|* Result set matching the given filter settings.

|`rs/address/filter/create`
|For creating a new favorite filter. The current filter settings of the UI including the specified name of the new filter are required.
a|* filter (new current filter)

|`rs/address/filter/select?id={filter-id}`
|For selecting a previous stored favorite filter. Same parameter as for initialList will be returned.
a|* UI layout
  * recent used filter by the user
  * Available favorites
  * Result set

|`rs/address/filter/update`
|For updating the current filter with the new filter settings done by the user.
|

|`rs/address/filter/delete`
|For deleting a favorite filter.
a|* Modified list of available favorites.

|`rs/address/filter/reset`
|Resets the current filter by default values.
a|* The default filter.


|`rs/address/reindexFull`
|For rebuilding the full search index for the enties (e. g. all addresses).
|
|===

==== Example of json format

.rs/address/initialList
[#src-listing]
[source,json]
----
{
  "ui": {
    "title": "Address list",
    "layout": [
      {
        "id": "resultSet",
        "type": "TABLE",
        "key": "el-1",
        "columns": [
          {
            "id": "address.lastUpdate",
            "title": "modified",
            "dataType": "DATE",
            "sortable": true,
            "formatter": "DATE",
            "type": "TABLE_COLUMN",
            "key": "el-2"
          },
   ...
  "data": {
    "resultSet": [
      {
        "address": {
          "name": "Reinhard",
        ...
----

=== Standard edit pages

Available REST calls:

[cols=3*,options="header"]
|===
|Rest call|Description|Return values

|`rs/address/{id}`
|Only the entity with the given id will be returned (not used by React frontend).
a|* The pure data object.

|`rs/address/edit?id={id}`
|Initial call for editing. If id is not given, the layout for creating a new object is returned.
a|* UI layout including action buttons.
* The object data (default values for new objects or all values for editing existing objects).

|`rs/address/history/{id}`
|For getting the complete history of changes of the given object.
a|* All entries of the history of changes.

|`rs/address/ac?property={property}&search={search}`
|Autocompletion: for searching all used property values (e. g. used locations of time sheets).
a|* All matching property values.

|`rs/address/ac?&search={search}`
|Autocompletion: for full text searching all objects matching the given search string.
a|* All matching objects (e. g. addresses).

|`rs/address/history/{id}`
|For getting the complete history of changes of the given object.
a|* All entries of the history of changes.

|`rs/address/saveorupdate`
|For saving or updating objects.
a|* The new URL to redirect, if any.

|`rs/address/clone`
|For cloning the current displayed object. Returns the initial UI layout for new objects including the create button instead of delete and update.
a|* UI layout including action buttons.
* The object as clone without id.

|`rs/address/markAsDeleted`
|For marking historizable objects as deleted. Fails for non historizable entities.
a|

|`rs/address/delete`
|For deleting objects from the data base without undo option. Fails for historizable entities.
a|

|`rs/address/cancel`
|Cancel the edit page.
a|* The new URL to redirect to.
|===

==== Example of json format

.rs/address/initialList
[#src-listing]
[source,json]
----
{
  "data": {
    "contactStatus": "ACTIVE",
    "name": "Schmidt",
    ...
  },
  "ui": {
    "title": "Edit address",
    "layout": [
      {
        "content": [
          {
            "length": 12,
            "type": "FIELDSET",
            "key": "el-2",
            "content": [
              ...
            {
              "id": "addressStatus",
              "type": "SELECT",
              "key": "el-9",
              "required": true,
              "label": "Address status",
              "values": [
                  {
                     "value": "UPTODATE",
                     ...
                  }]
            },
            ...
            {
              "id": "name",
              "maxLength": 255,
              "required": true,
              "focus": true,
              "dataType": "STRING",
              "label": "Name",
              "type": "INPUT",
              "key": "el-24"
            },
            ...
----

==== REST-API: JPA entities vs. DTO
For simple objects the JPA objects (BaseDO) may be used for the CRUD functionality through the REST-API. For more complex objects, especially if these objects
are embedded by other entities (users, tasks etc.) a DTO (data transfer object) has to be used.

In thanks to Kotlin, the creation of a DTO is very simple and efficient. Examples:

* `Address` The DTO for addresses is needed, because addresses may contain images with a special handling: https://github.com/micromata/projectforge/blob/develop/projectforge-rest/src/main/kotlin/org/projectforge/rest/dto/Address.kt
* `User` The DTO for users is needed, because user objects are embedded in other JPA entities: https://github.com/micromata/projectforge/blob/develop/projectforge-rest/src/main/kotlin/org/projectforge/rest/dto/User.kt
* `Task` Task is embedded by other entities as well: https://github.com/micromata/projectforge/blob/develop/projectforge-rest/src/main/kotlin/org/projectforge/rest/dto/Task.kt

The base class `BaseDTO` provides base functionality for the automatically transformation of DTO and BaseDO.

==== Putting all together in Kotlin code

Simple example (books)
[cols=3*,options="header"]
|===
|Class|Description|link

|`BookDO`|Defines the entity|https://github.com/micromata/projectforge/blob/develop/projectforge-business/src/main/kotlin/org/projectforge/business/book/BookDO.kt
|`BookDao`|Defines access rights and special functionality for books|https://github.com/micromata/projectforge/blob/develop/projectforge-business/src/main/kotlin/org/projectforge/business/book/BookDO.kt
|`BookRest`|Books with support of ReactJS as well as REST API for CRUD operations|https://github.com/micromata/projectforge/blob/develop/projectforge-rest/src/main/kotlin/org/projectforge/rest/BookRest.kt
|`BookStatus`|Enumeration of book status|https://github.com/micromata/projectforge/blob/develop/projectforge-business/src/main/java/org/projectforge/business/book/BookStatus.java
|===

Nothing more is needed to have a simple entity provided by ProjectForge!!! No HTML, no JavaScript, nothing else.

(The used BookFilter is deprecated and will be removed in 7.x., the new MagicFilter will replace most filters.)

Simple example (addresses) with more fields and UI layout with more fieldsets and columns (supporting different screen resolutions, responsive).
[cols=3*,options="header"]
|===
|Class|Description|link

|`AddressDO`|Defines the entity|https://github.com/micromata/projectforge/blob/develop/projectforge-business/src/main/kotlin/org/projectforge/business/address/AddressDO.kt
|`AddressDao`|Defines access rights and special functionality for addresses|https://github.com/micromata/projectforge/blob/develop/projectforge-business/src/main/kotlin/org/projectforge/business/book/BookDO.kt
|`AddressRest`|Addresses with support of ReactJS (responsive) as well as REST API for CRUD operations|https://github.com/micromata/projectforge/blob/develop/projectforge-business/src/main/java/org/projectforge/business/address/AddressDao.java
|'Address`|Data transfer object for the client. For simple objects, the BaseDO object may be used for the REST-CRUD functionality. For more complex objects providing special functionality, the usage of a DTO is required/recommended. |https://github.com/micromata/projectforge/blob/develop/projectforge-rest/src/main/kotlin/org/projectforge/rest/dto/Address.kt
|===

Nothing more is needed to have a simple entity provided by ProjectForge!!! No HTML, no JavaScript, nothing else.

(The used BookFilter is deprecated and will be removed in 7.x., the new MagicFilter will replace most filters.)


For creating own entities a description for smart plugins with a minimum of code is under construction.
