ProjectForge development documentation
=======================================
Micromata GmbH, Version {version}
:toc:
:toclevels: 4

:last-update-label: Copyright (C) 2019, Last updated

ifdef::env-github,env-browser[:outfilesuffix: .adoc]
link:index{outfilesuffix}[Top]

:sectnums:

== Migration guide

=== Version 6.x to version 7

. Configurationparameters changed
.. `config.xml:holiday.month` is now 1-based (1 - January, ..., 12 - December), was 0-based.
.. `projectforge.properties:projectforge.defaultFirstDayOfWeek=MONDAY` (full name of weekday: SUNDAY, ...)

. Configuration parameters moved from `config.xml` to `projectforge.properties`
   .. `config.xml:currencySymbol` -> `projectforge.properties:projectforge.currencySymbol=€`
   .. `config.xml:defaultLocale` -> `projectforge.properties:projectforge.defaultLocale=en`
   .. `config.xml:defaultTimeNotation` -> `projectforge.properties:projectforge.defaultTimeNotation=H24`
   .. `config.xml:firstDayOfWeek` -> `projectforge.properties:projectforge.defaultFirstDayOfWeek=MONDAY`
   .. `config.xml:excelPaperSize` -> `projectforge.properties:projectforge.excelPaperSize=DINA4`

. PhoneLookupServlet moved from `phoneLookup` to `rsPublic/phoneLookup`
