==== Testinstanz installieren

Die aktuellste Version dieser Datei befindet sich https://github.com/micromata/projectforge/blob/develop/doc/Testinstallation-deutsch.adoc[hier].

===== Download

`projectforge-application-8.1-xxx.jar` herunterladen

===== Java 21 installieren
Open-JDK 21 installieren bzw. entsprechendes Docker-Image verwenden.

==== Erststart

Starten über `java -jar projectforge-application-8.1-xxx.jar`

. (2) Console based wizard wählen (falls GUI nicht erreichbar ist, sonst kann auch der grafische gewählt werden).
    .. Homeverzeichnis auswählen (z. B. `~/projectforge`), RETURN DRÜCKEN
    .. Parameter unverändert übernehmen.
    .. Finish wählen und Start abwarten.

Es wird standardmäßig eine Embedded-Database verwendet. Alternativ kann eine Postgres-Datenbank verwendet werden.

Browser öffnen: `http://localhost:8080` öffnen

. `Testsystem` auswählen (es wird eine Datenbank mit Testdaten erstellt.)
. Passwort festlegen
. E-Mail Adresse eingeben, z. B. `egal@localhost` (für 2. Faktor)
. Fertig stellen klicken.

===== System herunterfahren
Einfach `CTRL-C` im Terminal drücken.

===== Anpassungen
Anpassungen in der Konfiguration können hier durchgeführt werden:

Anpassen in `~/ProjectForge/projectforge.properties` (irgendwo hinzufügen):

[source]
----
# Im development.mode wird der 2FA-Code, der sonst per SMS versendet wird auch in den Logs ausgegeben. Außerdem ist das Logfile viel "gesprächiger".
projectforge.development.mode=true
# ProjectForge denkt hiermit, es wäre ein SMS-Gateway aktiviert:
projectforge.sms.url=http://smsgw.localhost/api.php
----

===== Wiederstart

Starten über `java -jar projectforge-application-8.1-xxx.jar`

===== 2. Faktor (ohne Mailserver und SMS-Gateway) simulieren:
- Als admin/**** anmelden.
- Unter *Administration* -> *Users* -> User *admin* auswählen.
- Mobilfunknummer '123456789' eintragen.

Nun kann der 2. Faktor per SMS versendet werden. Es gibt eine Fehlermeldung, aber aufgrund der obigen Einstellung `projectforge.development.mode=true` in `~/ProjectForge/projectforge.properties` wird der 2. Faktor in den Logs zu Debug-Zwecken ausgegeben.

Anschließend kann Yubikey, Google Authenticator oder andere 2FA-Methoden konfiguruiert werden.

===== Weitere Konfigmöglichkeiten

Hier ist die Datei mit allen Konfigurationsmöglichkeiten:

https://github.com/micromata/projectforge/blob/develop/projectforge-business/src/main/resources/application.properties[application.properties]

===== Reset
Einfach herunterfahren, `~/ProjectForge` löschen (Datenbank ist dann gelöscht) und von vorn beginnen.

===== Doku
Doku liegt unter

. https://github.com/micromata/projectforge[Github]
. https://www.projectforge.org/[www.projectforge.org]
