/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":projectforge-common"))
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.javax.jcr.jcr)
    api(libs.org.apache.jackrabbit.oak.jcr)
    api(libs.org.apache.jackrabbit.oak.segment.tar)
    api(libs.io.dropwizard.metrics.metrics.core)
    api(libs.net.lingala.zip4j.zip4j)
    api(libs.com.fasterxml.jackson.core.jackson.core)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    testImplementation(project(":projectforge-commons-test"))
}

description = "projectforge-jcr"
