ALTER TABLE T_SCRIPT ADD COLUMN type CHARACTER VARYING(20);
ALTER TABLE T_SCRIPT ADD COLUMN sudo boolean;
ALTER TABLE T_SCRIPT ADD COLUMN full_access_group_ids CHARACTER VARYING(4000);
ALTER TABLE T_SCRIPT ADD COLUMN full_access_user_ids CHARACTER VARYING(4000);
ALTER TABLE T_SCRIPT ADD COLUMN readonly_access_group_ids CHARACTER VARYING(4000);
ALTER TABLE T_SCRIPT ADD COLUMN readonly_access_user_ids CHARACTER VARYING(4000);
ALTER TABLE T_SCRIPT ADD COLUMN minimal_access_group_ids CHARACTER VARYING(4000);
ALTER TABLE T_SCRIPT ADD COLUMN minimal_access_user_ids CHARACTER VARYING(4000);
