-- Add date of creations for implementing expiring periods or for information purposes:
ALTER TABLE T_PF_USER_AUTHENTICATIONS ADD COLUMN calendar_export_token_creation_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE T_PF_USER_AUTHENTICATIONS ADD COLUMN dav_token_creation_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE T_PF_USER_AUTHENTICATIONS ADD COLUMN rest_client_token_creation_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE T_PF_USER_AUTHENTICATIONS ADD COLUMN stay_logged_in_key_creation_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE T_PF_USER_AUTHENTICATIONS ADD COLUMN authenticator_key_creation_date TIMESTAMP WITHOUT TIME ZONE;
