/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":projectforge-rest"))
    api(libs.org.springframework.boot.starter.webflux)
    api(libs.org.springframework.spring.orm)
    api(libs.org.springframework.spring.context)
    compileOnly(libs.jakarta.annotation.jakarta.annotation.api)
    testImplementation(project(":projectforge-commons-test"))
    testImplementation(project(":projectforge-business-test"))
}

description = "org.projectforge.plugins.datatransfer"
