/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-jdbc:3.3.5")
    api("io.github.microutils:kotlin-logging-jvm:3.0.5")
    api("jakarta.xml.bind:jakarta.xml.bind-api:4.0.2")
    api("com.sun.xml.bind:jaxb-core:4.0.5")
    api("com.sun.xml.bind:jaxb-impl:4.0.5")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.3.5")
    testImplementation("org.junit.platform:junit-platform-launcher:1.10.3")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.5")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.10.5")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.10.5")
    testImplementation("org.mockito:mockito-core:5.12.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.12.0")
    testImplementation("org.mockito.kotlin:mockito-kotlin:5.4.0")
    compileOnly("org.slf4j:log4j-over-slf4j:2.0.16")
}

group = "org.projectforge"
version = "8.0.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
