/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":projectforge-common"))
    api(project(":projectforge-business"))
    api(project(":projectforge-rest"))
    api(libs.org.apache.wicket.wicket.myextensions)
    api(libs.org.apache.wicket.wicket.spring)
    api(libs.org.apache.wicket.wicket.tester)
    api(libs.jakarta.servlet.jsp.jakarta.servlet.jsp.api)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.org.wicketstuff.wicketstuff.html5)
    api(libs.org.wicketstuff.wicketstuff.select2)
    api(libs.com.google.code.gson.gson)
    api(libs.org.mozilla.rhino)
    testImplementation(project(":projectforge-commons-test"))
    testImplementation(project(":projectforge-business-test"))
    compileOnly(libs.jakarta.servlet.jakarta.servlet.api)
}

description = "projectforge-wicket"
