/////////////////////////////////////////////////////////////////////////////
//
// Project ProjectForge Community Edition
//         www.projectforge.org
//
// Copyright (C) 2001-2026 Micromata GmbH, Germany (www.micromata.com)
//
// ProjectForge is dual-licensed.
//
// This community edition is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation; version 3 of the License.
//
// This community edition is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, see http://www.gnu.org/licenses/.
//
/////////////////////////////////////////////////////////////////////////////

package org.projectforge.development

import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.node.ObjectNode
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.io.File
import java.nio.charset.StandardCharsets
import java.time.LocalDate

/**
 * Guards the changelog generated by [GenerateChangelogMain] from `changelog/changelog.json`: the
 * conversion of the markdown subset to AsciiDoc, the validation of the source and that the generated
 * files of the website and of projectforge-next are up to date (fix: run [DevelopmentMainForRelease]).
 */
class GenerateChangelogMainTest {
  @Test
  fun inlineMarkdownIsConvertedToAsciiDoc() {
    assertEquals("plain text", GenerateChangelogMain.inlineToAdoc("plain text"))
    assertEquals("**bold** and __italic__", GenerateChangelogMain.inlineToAdoc("**bold** and *italic*"))
    assertEquals("[red]##warning##", GenerateChangelogMain.inlineToAdoc("{red}warning{/red}"))
    assertEquals("[red]##**strong warning**## -", GenerateChangelogMain.inlineToAdoc("{red}**strong warning**{/red} -"))
    assertEquals(
      "see https://example.org/a_b_c[the **docs**]",
      GenerateChangelogMain.inlineToAdoc("see [the **docs**](https://example.org/a_b_c)")
    )
    assertEquals("`+*not* bold+`", GenerateChangelogMain.inlineToAdoc("`*not* bold`"))
    // Stars that aren't emphasis stay as they are.
    assertEquals("tomcat.* and app*", GenerateChangelogMain.inlineToAdoc("tomcat.* and app*"))
    assertEquals("2 * 3 * 4", GenerateChangelogMain.inlineToAdoc("2 * 3 * 4"))
  }

  @Test
  fun blocksKeepParagraphsAndLists() {
    assertEquals(
      "First **paragraph**.\n\nList:\n- one\n- __two__",
      GenerateChangelogMain.blockToAdoc("First **paragraph**.\n\nList:\n- one\n- *two*")
    )
  }

  @Test
  fun unsupportedFormattingIsRejected() {
    fun errors(text: String, inline: Boolean = false, item: Boolean = false) =
      mutableListOf<String>().also { GenerateChangelogMain.validateText(text, "t", it, inline, item) }
    assertTrue(errors("**bold** {red}red{/red} [link](https://x.org) - dash").isEmpty())
    assertTrue(errors("item\n- sub one\n- sub two", item = true).isEmpty())
    assertEquals(1, errors("<b>html</b>").size)
    assertEquals(1, errors("# heading").size)
    assertEquals(1, errors("{blue}text{/blue}").size)
    assertEquals(1, errors("{red}unbalanced").size)
    assertEquals(1, errors("* star list").size)
    assertEquals(1, errors("liquid {{ page.title }}").size)
    assertEquals(1, errors("two\nlines", inline = true).size)
    assertEquals(1, errors("item\n\n- sub", item = true).size)
    val titleErrors = mutableListOf<String>()
    GenerateChangelogMain.validateTitle("Plain title (2026), with: punctuation", "t", titleErrors)
    GenerateChangelogMain.validateTitle("**Bold** title", "t", titleErrors)
    assertEquals(1, titleErrors.size, titleErrors.toString())
  }

  @Test
  fun invalidReleasesAreReported() {
    val root = ObjectMapper().readTree(
      """
      {"news": [{"version": "9", "date": "2026-01-01", "title": "N", "text": "x"}], "releases": [
        {"id": "b", "version": "2", "date": "2026-01-01", "title": "B", "fromCommit": "aaaaaaa", "toCommit": "bbbbbbb",
         "sections": [{"type": "improved", "items": ["x"]}]},
        {"id": "b", "version": "1", "date": "2026-02-01", "title": "A", "fromCommit": "0000000", "toCommit": "ccccccc",
         "sections": [{"type": "unknown", "items": ["x"]}]}
      ]}
      """.trimIndent()
    )
    val errors = GenerateChangelogMain.validate(root)
    assertTrue(errors.any { it.contains("must be the 'toCommit'") }, errors.toString())
    assertTrue(errors.any { it.contains("duplicate id") }, errors.toString())
    assertTrue(errors.any { it.contains("sorted by date") }, errors.toString())
    assertTrue(errors.any { it.contains("unknown type") }, errors.toString())
    assertTrue(errors.any { it.contains("no release with version 9") }, errors.toString())
  }

  @Test
  fun newsIsShownAboveTheNewestReleaseOfItsVersion() {
    val root = ObjectMapper().readTree(
      """
      {"news": [{"version": "8.2"}, {"version": "8.1"}], "releases": [
        {"id": "s2", "version": "8.2-SNAPSHOT"}, {"id": "s1", "version": "8.2-SNAPSHOT"},
        {"id": "r81", "version": "8.1"}, {"id": "r811", "version": "8.1.1"}
      ]}
      """.trimIndent()
    )
    assertEquals(listOf("s2", "r81"), GenerateChangelogMain.newsAnchors(root))
  }

  @Test
  fun newsIsShownAboveTheNewestBuildOfItsVersion() {
    val root = ObjectMapper().readTree(
      """
      {"news": [{"version": "8.2"}], "releases": [
        {"id": "s", "version": "8.2.38-SNAPSHOT"}, {"id": "r37", "version": "8.2.37"}, {"id": "r0", "version": "8.2.0"}
      ]}
      """.trimIndent()
    )
    assertEquals(listOf("s"), GenerateChangelogMain.newsAnchors(root))
    assertEquals("8.2", GenerateChangelogMain.newsVersion("8.2.37"))
    assertEquals("8.2", GenerateChangelogMain.newsVersion("8.2-SNAPSHOT"))
  }

  @Test
  fun releaseNeedsItsEntryAndANewsForAMajorOrMinorVersion() {
    val mapper = ObjectMapper()
    val today = LocalDate.of(2026, 10, 6)
    fun check(version: String, releaseVersion: String = version, tag: String = "$releaseVersion-RELEASE", news: String = "8.2"): List<String> {
      val root = mapper.readTree(
        """
        {"news": [{"version": "$news", "date": "2026-10-01", "title": "News", "text": "Text"}], "releases": [
          {"id": "r", "version": "$releaseVersion", "date": "2026-10-06", "title": "Release", "tag": "$tag",
           "sections": [{"type": "fixed", "items": ["bug"]}]},
          {"id": "old", "version": "8.2.1", "date": "2026-09-01", "title": "Old", "tag": "8.2.1-RELEASE",
           "sections": [{"type": "fixed", "items": ["bug"]}]}
        ]}
        """.trimIndent()
      )
      val translation = mapper.readTree(
        """
        {"news": {"$news": {"title": "Neu", "text": "Text"}}, "releases": {
          "r": {"title": "Release", "sections": [{"type": "fixed", "items": ["Fehler"]}]},
          "old": {"title": "Alt", "sections": [{"type": "fixed", "items": ["Fehler"]}]}}}
        """.trimIndent()
      )
      return GenerateChangelogMain.checkRelease(root, translation, version, today)
    }
    assertEquals(emptyList<String>(), check("8.2.37"))
    assertEquals(emptyList<String>(), check("8.2.0"))
    assertTrue(check("8.3.0").any { it.contains("needs a news with version \"8.3\"") })
    assertTrue(check("8.2.38", releaseVersion = "8.2.37").any { it.contains("newest release must be the one of version 8.2.38") })
    assertTrue(check("8.2.37", tag = "8.2.37").any { it.contains("'tag' must be '8.2.37-RELEASE'") })
    assertTrue(check("8.2.1").any { it.contains("released already") })
    assertTrue(check("8.2").single().contains("no release version"))
  }

  @Test
  fun releaseNotesAreGitHubMarkdown() {
    val root = ObjectMapper().readTree(
      """
      {"news": [{"version": "8.3", "date": "2026-10-01", "title": "News title", "text": "News text.",
                 "highlights": ["**One**"]}],
       "releases": [{"id": "r", "version": "8.3.0", "date": "2026-10-06", "title": "Release",
         "intro": ["{red}**Update recommended.**{/red} Intro."],
         "sections": [{"type": "fixed", "items": ["bug\n- detail", {"title": "Group", "items": ["a"]}]}]}]}
      """.trimIndent()
    )
    assertEquals(
      """
      # ProjectForge 8.3.0

      **⚠️ Update recommended.** Intro.

      ## News title

      News text.

      - **One**

      ## Fixed

      - bug
        - detail
      - **Group**
        - a

      """.trimIndent(),
      GenerateChangelogMain.releaseNotesMarkdown(root, "8.3.0")
    )
    // A build lists its own changes only.
    (root["releases"][0] as ObjectNode).put("version", "8.3.1")
    assertTrue(!GenerateChangelogMain.releaseNotesMarkdown(root, "8.3.1").contains("News title"))
  }

  @Test
  fun releaseNotesIncludeTheUnpublishedReleasesSinceTheLastPublishedOne() {
    val root = ObjectMapper().readTree(
      """
      {"news": [{"version": "8.3", "date": "2026-10-01", "title": "News title", "text": "News text."}],
       "releases": [
         {"id": "r3", "version": "8.3.3", "tag": "8.3.3-RELEASE",
          "sections": [{"type": "fixed", "items": ["fix 3"]}]},
         {"id": "s", "version": "8.3.3-SNAPSHOT", "sections": [{"type": "added", "items": ["snapshot"]}]},
         {"id": "r2", "version": "8.3.2", "tag": "8.3.2-RELEASE", "published": false,
          "intro": ["Intro 2."], "sections": [{"type": "added", "items": ["feature 2"]}, {"type": "fixed", "items": ["fix 2"]}]},
         {"id": "r1", "version": "8.3.1", "tag": "8.3.1-RELEASE", "published": false,
          "sections": [{"type": "fixed", "items": ["fix 1"]}]},
         {"id": "r0", "version": "8.3.0", "tag": "8.3.0-RELEASE",
          "sections": [{"type": "fixed", "items": ["fix 0"]}]}]}
      """.trimIndent()
    )
    assertEquals(
      """
      # ProjectForge 8.3.3

      Also includes the changes of 8.3.2 and 8.3.1, released without downloads.

      Intro 2.

      ## Fixed

      - fix 3
      - fix 2
      - fix 1

      ## Added

      - feature 2

      """.trimIndent(),
      GenerateChangelogMain.releaseNotesMarkdown(root, "8.3.3")
    )
    // A published release directly after a published one lists its own changes only.
    assertEquals(listOf("r0"), GenerateChangelogMain.aggregatedReleases(root, "8.3.0").map { it["id"].asText() })
  }

  @Test
  fun onlyATaggedReleaseWithoutDownloadLinkCanBeUnpublished() {
    val root = ObjectMapper().readTree(
      """
      {"news": [], "releases": [
        {"id": "a", "version": "1.0.2", "date": "2026-01-03", "title": "A", "tag": "1.0.2-RELEASE", "published": "no",
         "sections": [{"type": "fixed", "items": ["bug"]}]},
        {"id": "b", "version": "1.0.1", "date": "2026-01-02", "title": "B", "tag": "1.0.1-RELEASE", "published": false,
         "downloadLink": true, "sections": [{"type": "fixed", "items": ["bug"]}]},
        {"id": "c", "version": "1.0.1-SNAPSHOT", "date": "2026-01-01", "title": "C", "published": false,
         "fromCommit": "aaaaaaa", "toCommit": "bbbbbbb", "sections": [{"type": "fixed", "items": ["bug"]}]}
      ]}
      """.trimIndent()
    )
    val errors = GenerateChangelogMain.validate(root)
    assertTrue(errors.any { it.contains("(a): 'published' must be true or false") }, errors.toString())
    assertTrue(errors.any { it.contains("(b): an unpublished release has no download link") }, errors.toString())
    assertTrue(errors.any { it.contains("(c): only a tagged release can be unpublished") }, errors.toString())
  }

  @Test
  fun translationKeepsTheStructureOfTheSource() {
    val mapper = ObjectMapper()
    val root = mapper.readTree(
      """
      {"news": [{"version": "1", "date": "2026-01-01", "title": "News", "text": "Text", "highlights": ["one"]}],
       "releases": [{"id": "r1", "version": "1", "date": "2026-01-01", "title": "Release", "tag": "1-RELEASE",
         "sections": [{"type": "fixed", "items": ["bug\n- detail", {"title": "Group", "items": ["a", "b"]}]}]}]}
      """.trimIndent()
    )
    val translation = mapper.readTree(
      """
      {"news": {"1": {"title": "Neuigkeit", "text": "Text", "highlights": ["eins"]}},
       "releases": {"r1": {"title": "Release", "sections": [{"type": "fixed",
         "items": ["Fehler\n- Detail", {"title": "Gruppe", "items": ["a", "b"]}]}]}}}
      """.trimIndent()
    )
    assertEquals(emptyList<String>(), GenerateChangelogMain.validateTranslation(root, translation))
    val translated = GenerateChangelogMain.translate(root, translation)
    assertEquals("Neuigkeit", translated["news"][0]["title"].asText())
    assertEquals("2026-01-01", translated["news"][0]["date"].asText())
    assertEquals("Gruppe", translated["releases"][0]["sections"][0]["items"][1]["title"].asText())
    assertEquals("1-RELEASE", translated["releases"][0]["tag"].asText())

    val broken = mapper.readTree(
      """
      {"news": {"2": {"title": "X", "text": "X"}},
       "releases": {"r1": {"title": "Release", "version": "9", "sections": [{"type": "added",
         "items": ["Fehler", "Gruppe"]}]}}}
      """.trimIndent()
    )
    val errors = GenerateChangelogMain.validateTranslation(root, broken)
    assertTrue(errors.any { it.contains("no news of this version") }, errors.toString())
    assertTrue(errors.any { it.contains("news 1: the translation is missing") }, errors.toString())
    assertTrue(errors.any { it.contains("'version' can't be translated") }, errors.toString())
    assertTrue(errors.any { it.contains("the type must be 'fixed'") }, errors.toString())
    assertTrue(errors.any { it.contains("number of sub list lines") }, errors.toString())
    assertTrue(errors.any { it.contains("must be a group") }, errors.toString())
  }

  @Test
  fun fragmentsHoldTheEnglishAndGermanTextOfAnItemOrGroup() {
    fun parse(name: String, content: String): Pair<GenerateChangelogMain.Fragment?, List<String>> {
      val errors = mutableListOf<String>()
      return GenerateChangelogMain.parseFragment(name, content, errors) to errors
    }
    val (item, itemErrors) = parse("20261006-item.json", """{"type": "added", "en": "Item\n- sub", "de": "Punkt\n- unter"}""")
    assertEquals(emptyList<String>(), itemErrors)
    assertEquals(LocalDate.of(2026, 10, 6), item!!.date)
    assertEquals("Punkt\n- unter", item.de.asText())
    val (group, groupErrors) = parse(
      "20261007-group.json",
      """{"type": "changed", "en": "Group", "de": "Gruppe", "items": [{"en": "a", "de": "b"}]}"""
    )
    assertEquals(emptyList<String>(), groupErrors)
    assertEquals("""{"title":"Gruppe","items":["b"]}""", group!!.de.toString())

    fun error(name: String, content: String) = parse(name, content).second.single()
    val valid = """{"type": "added", "en": "a", "de": "b"}"""
    assertTrue(error("item.json", valid).contains("yyyyMMdd"))
    assertTrue(error("20261306-a.json", valid).contains("yyyyMMdd"))
    assertTrue(error("20261006-a.json", "{").contains("invalid JSON"))
    assertTrue(error("20261006-a.json", """{"type": "new", "en": "a", "de": "b"}""").contains("unknown type"))
    assertTrue(error("20261006-a.json", """{"type": "added", "en": "a"}""").contains("'de' is missing"))
    assertTrue(error("20261006-a.json", """{"type": "added", "en": "a", "de": "b", "id": 1}""").contains("unknown field 'id'"))
    assertTrue(error("20261006-a.json", """{"type": "added", "en": "a\n- s", "de": "b"}""").contains("sub list lines"))
    assertTrue(error("20261006-a.json", """{"type": "added", "en": "a", "de": "<b>b</b>"}""").contains("raw HTML"))
    assertTrue(error("20261006-a.json", """{"type": "added", "en": "G", "de": "G", "items": []}""").contains("non-empty"))
    assertTrue(
      error("20261006-a.json", """{"type": "added", "en": "G", "de": "G", "items": [{"en": "a"}]}""")
        .contains("'de' is missing")
    )
  }

  @Test
  fun foldAddsTheFragmentsAtTheSamePositionToBothLanguages() {
    val mapper = ObjectMapper()
    val root = mapper.readTree(
      """
      {"news": [], "releases": [{"id": "s", "version": "1.0.1-SNAPSHOT", "date": "2026-10-01", "title": "S",
        "fromCommit": "aaaaaaa", "toCommit": "bbbbbbb",
        "sections": [{"type": "added", "items": ["old"]}, {"type": "fixed", "items": ["bug"]}]}]}
      """.trimIndent()
    )
    val translation = mapper.readTree(
      """
      {"news": {}, "releases": {"s": {"title": "S",
        "sections": [{"type": "added", "items": ["alt"]}, {"type": "fixed", "items": ["Fehler"]}]}}}
      """.trimIndent()
    )
    val fragments = listOf(
      fragment("20261002-a.json", """{"type": "fixed", "en": "fix", "de": "Korrektur"}"""),
      fragment("20261003-b.json", """{"type": "improved", "en": "better", "de": "besser"}"""),
      fragment("20261004-c.json", """{"type": "added", "en": "new", "de": "neu"}"""),
    )
    val (folded, foldedTranslation) = GenerateChangelogMain.fold(root, translation, "s", fragments)
    assertEquals(
      """[{"type":"added","items":["old","new"]},{"type":"improved","items":["better"]},{"type":"fixed","items":["bug","fix"]}]""",
      folded["releases"][0]["sections"].toString()
    )
    assertEquals(
      """[{"type":"added","items":["alt","neu"]},{"type":"improved","items":["besser"]},{"type":"fixed","items":["Fehler","Korrektur"]}]""",
      foldedTranslation["releases"]["s"]["sections"].toString()
    )
    assertEquals(emptyList<String>(), GenerateChangelogMain.validate(folded))
    assertEquals(emptyList<String>(), GenerateChangelogMain.validateTranslation(folded, foldedTranslation))
    // The sources themselves are unchanged.
    assertEquals(2, root["releases"][0]["sections"].size())
    // A release entry may have no sections of its own, they all come from the fragments.
    val empty = root.deepCopy<ObjectNode>().also { (it["releases"][0] as ObjectNode).remove("sections") }
    val emptyTranslation = translation.deepCopy<ObjectNode>().also { (it["releases"]["s"] as ObjectNode).remove("sections") }
    val (onlyFragments, onlyFragmentsTranslation) = GenerateChangelogMain.fold(empty, emptyTranslation, "s", fragments)
    assertEquals(listOf("added", "improved", "fixed"), onlyFragments["releases"][0]["sections"].map { it["type"].asText() })
    assertEquals(emptyList<String>(), GenerateChangelogMain.validateTranslation(onlyFragments, onlyFragmentsTranslation))

    // projectforge-next shows the fragments as the newest release.
    val (next, nextTranslation) = GenerateChangelogMain.withUnreleased(root, translation, fragments)
    val unreleased = next["releases"][0]
    assertEquals(GenerateChangelogMain.UNRELEASED_ID, unreleased["id"].asText())
    assertEquals("1.0.1-SNAPSHOT", unreleased["version"].asText())
    assertEquals("2026-10-04", unreleased["date"].asText())
    assertEquals(listOf("added", "improved", "fixed"), unreleased["sections"].map { it["type"].asText() })
    assertEquals(2, next["releases"].size())
    assertEquals(emptyList<String>(), GenerateChangelogMain.validateTranslation(next, nextTranslation))
    assertEquals(
      "neu",
      GenerateChangelogMain.translate(next, nextTranslation)["releases"][0]["sections"][0]["items"][0].asText()
    )
    assertEquals(root to translation, GenerateChangelogMain.withUnreleased(root, translation, emptyList()))
  }

  @Test
  fun sourcesAreWrittenInTheirOwnFormat() {
    val rootDir = GenerateChangelogMain.resolveRootDir()
    listOf(GenerateChangelogMain.SOURCE, GenerateChangelogMain.SOURCE_DE).forEach { path ->
      val text = File(rootDir, path).readText(StandardCharsets.UTF_8)
      assertEquals(text, GenerateChangelogMain.sourceJson(ObjectMapper().readTree(text)), path)
    }
  }

  private fun fragment(name: String, content: String): GenerateChangelogMain.Fragment {
    val errors = mutableListOf<String>()
    return GenerateChangelogMain.parseFragment(name, content, errors).also { assertEquals(emptyList<String>(), errors) }!!
  }

  @Test
  fun generatedFilesAreUpToDate() {
    val rootDir = GenerateChangelogMain.resolveRootDir()
    assertTrue(
      File(rootDir, GenerateChangelogMain.SOURCE).isFile,
      "Cannot locate the repository root, resolved '${rootDir.absolutePath}' has no ${GenerateChangelogMain.SOURCE}."
    )
    val generated = GenerateChangelogMain.generate(rootDir)
    generated.forEach { (path, expected) ->
      val file = File(rootDir, path)
      assertTrue(file.isFile, "Generated changelog file is missing: ${file.absolutePath}")
      assertEquals(
        expected,
        file.readText(StandardCharsets.UTF_8),
        "$path is out of date or was edited by hand. Edit ${GenerateChangelogMain.SOURCE} and run" +
            " DevelopmentMainForRelease."
      )
    }
    assertEquals(
      emptyList<File>(),
      GenerateChangelogMain.staleFiles(rootDir, generated.keys),
      "Files not generated from ${GenerateChangelogMain.SOURCE}, run DevelopmentMainForRelease."
    )
  }
}
