/////////////////////////////////////////////////////////////////////////////
//
// Project ProjectForge Community Edition
//         www.projectforge.org
//
// Copyright (C) 2001-2026 Micromata GmbH, Germany (www.micromata.com)
//
// ProjectForge is dual-licensed.
//
// This community edition is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation; version 3 of the License.
//
// This community edition is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, see http://www.gnu.org/licenses/.
//
/////////////////////////////////////////////////////////////////////////////

package org.projectforge.development

import com.fasterxml.jackson.databind.ObjectMapper
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.io.File
import java.nio.charset.StandardCharsets

/**
 * Guards the changelog generated by [GenerateChangelogMain] from `changelog/changelog.json`: the
 * conversion of the markdown subset to AsciiDoc, the validation of the source and that the generated
 * files of the website and of projectforge-next are up to date (fix: run [DevelopmentMainForRelease]).
 */
class GenerateChangelogMainTest {
  @Test
  fun inlineMarkdownIsConvertedToAsciiDoc() {
    assertEquals("plain text", GenerateChangelogMain.inlineToAdoc("plain text"))
    assertEquals("**bold** and __italic__", GenerateChangelogMain.inlineToAdoc("**bold** and *italic*"))
    assertEquals("[red]##warning##", GenerateChangelogMain.inlineToAdoc("{red}warning{/red}"))
    assertEquals("[red]##**strong warning**## -", GenerateChangelogMain.inlineToAdoc("{red}**strong warning**{/red} -"))
    assertEquals(
      "see https://example.org/a_b_c[the **docs**]",
      GenerateChangelogMain.inlineToAdoc("see [the **docs**](https://example.org/a_b_c)")
    )
    assertEquals("`+*not* bold+`", GenerateChangelogMain.inlineToAdoc("`*not* bold`"))
    // Stars that aren't emphasis stay as they are.
    assertEquals("tomcat.* and app*", GenerateChangelogMain.inlineToAdoc("tomcat.* and app*"))
    assertEquals("2 * 3 * 4", GenerateChangelogMain.inlineToAdoc("2 * 3 * 4"))
  }

  @Test
  fun blocksKeepParagraphsAndLists() {
    assertEquals(
      "First **paragraph**.\n\nList:\n- one\n- __two__",
      GenerateChangelogMain.blockToAdoc("First **paragraph**.\n\nList:\n- one\n- *two*")
    )
  }

  @Test
  fun unsupportedFormattingIsRejected() {
    fun errors(text: String, inline: Boolean = false, item: Boolean = false) =
      mutableListOf<String>().also { GenerateChangelogMain.validateText(text, "t", it, inline, item) }
    assertTrue(errors("**bold** {red}red{/red} [link](https://x.org) - dash").isEmpty())
    assertTrue(errors("item\n- sub one\n- sub two", item = true).isEmpty())
    assertEquals(1, errors("<b>html</b>").size)
    assertEquals(1, errors("# heading").size)
    assertEquals(1, errors("{blue}text{/blue}").size)
    assertEquals(1, errors("{red}unbalanced").size)
    assertEquals(1, errors("* star list").size)
    assertEquals(1, errors("liquid {{ page.title }}").size)
    assertEquals(1, errors("two\nlines", inline = true).size)
    assertEquals(1, errors("item\n\n- sub", item = true).size)
    val titleErrors = mutableListOf<String>()
    GenerateChangelogMain.validateTitle("Plain title (2026), with: punctuation", "t", titleErrors)
    GenerateChangelogMain.validateTitle("**Bold** title", "t", titleErrors)
    assertEquals(1, titleErrors.size, titleErrors.toString())
  }

  @Test
  fun invalidReleasesAreReported() {
    val root = ObjectMapper().readTree(
      """
      {"news": [{"version": "9", "date": "2026-01-01", "title": "N", "text": "x"}], "releases": [
        {"id": "b", "version": "2", "date": "2026-01-01", "title": "B", "fromCommit": "aaaaaaa", "toCommit": "bbbbbbb",
         "sections": [{"type": "improved", "items": ["x"]}]},
        {"id": "b", "version": "1", "date": "2026-02-01", "title": "A", "fromCommit": "0000000", "toCommit": "ccccccc",
         "sections": [{"type": "unknown", "items": ["x"]}]}
      ]}
      """.trimIndent()
    )
    val errors = GenerateChangelogMain.validate(root)
    assertTrue(errors.any { it.contains("must be the 'toCommit'") }, errors.toString())
    assertTrue(errors.any { it.contains("duplicate id") }, errors.toString())
    assertTrue(errors.any { it.contains("sorted by date") }, errors.toString())
    assertTrue(errors.any { it.contains("unknown type") }, errors.toString())
    assertTrue(errors.any { it.contains("no release with version 9") }, errors.toString())
  }

  @Test
  fun newsIsShownAboveTheNewestReleaseOfItsVersion() {
    val root = ObjectMapper().readTree(
      """
      {"news": [{"version": "8.2"}, {"version": "8.1"}], "releases": [
        {"id": "s2", "version": "8.2-SNAPSHOT"}, {"id": "s1", "version": "8.2-SNAPSHOT"},
        {"id": "r81", "version": "8.1"}, {"id": "r811", "version": "8.1.1"}
      ]}
      """.trimIndent()
    )
    assertEquals(listOf("s2", "r81"), GenerateChangelogMain.newsAnchors(root))
  }

  @Test
  fun translationKeepsTheStructureOfTheSource() {
    val mapper = ObjectMapper()
    val root = mapper.readTree(
      """
      {"news": [{"version": "1", "date": "2026-01-01", "title": "News", "text": "Text", "highlights": ["one"]}],
       "releases": [{"id": "r1", "version": "1", "date": "2026-01-01", "title": "Release", "tag": "1-RELEASE",
         "sections": [{"type": "fixed", "items": ["bug\n- detail", {"title": "Group", "items": ["a", "b"]}]}]}]}
      """.trimIndent()
    )
    val translation = mapper.readTree(
      """
      {"news": {"1": {"title": "Neuigkeit", "text": "Text", "highlights": ["eins"]}},
       "releases": {"r1": {"title": "Release", "sections": [{"type": "fixed",
         "items": ["Fehler\n- Detail", {"title": "Gruppe", "items": ["a", "b"]}]}]}}}
      """.trimIndent()
    )
    assertEquals(emptyList<String>(), GenerateChangelogMain.validateTranslation(root, translation))
    val translated = GenerateChangelogMain.translate(root, translation)
    assertEquals("Neuigkeit", translated["news"][0]["title"].asText())
    assertEquals("2026-01-01", translated["news"][0]["date"].asText())
    assertEquals("Gruppe", translated["releases"][0]["sections"][0]["items"][1]["title"].asText())
    assertEquals("1-RELEASE", translated["releases"][0]["tag"].asText())

    val broken = mapper.readTree(
      """
      {"news": {"2": {"title": "X", "text": "X"}},
       "releases": {"r1": {"title": "Release", "version": "9", "sections": [{"type": "added",
         "items": ["Fehler", "Gruppe"]}]}}}
      """.trimIndent()
    )
    val errors = GenerateChangelogMain.validateTranslation(root, broken)
    assertTrue(errors.any { it.contains("no news of this version") }, errors.toString())
    assertTrue(errors.any { it.contains("news 1: the translation is missing") }, errors.toString())
    assertTrue(errors.any { it.contains("'version' can't be translated") }, errors.toString())
    assertTrue(errors.any { it.contains("the type must be 'fixed'") }, errors.toString())
    assertTrue(errors.any { it.contains("number of sub list lines") }, errors.toString())
    assertTrue(errors.any { it.contains("must be a group") }, errors.toString())
  }

  @Test
  fun generatedFilesAreUpToDate() {
    val rootDir = GenerateChangelogMain.resolveRootDir()
    assertTrue(
      File(rootDir, GenerateChangelogMain.SOURCE).isFile,
      "Cannot locate the repository root, resolved '${rootDir.absolutePath}' has no ${GenerateChangelogMain.SOURCE}."
    )
    val generated = GenerateChangelogMain.generate(rootDir)
    generated.forEach { (path, expected) ->
      val file = File(rootDir, path)
      assertTrue(file.isFile, "Generated changelog file is missing: ${file.absolutePath}")
      assertEquals(
        expected,
        file.readText(StandardCharsets.UTF_8),
        "$path is out of date or was edited by hand. Edit ${GenerateChangelogMain.SOURCE} and run" +
            " DevelopmentMainForRelease."
      )
    }
    assertEquals(
      emptyList<File>(),
      GenerateChangelogMain.staleFiles(rootDir, generated.keys),
      "Files not generated from ${GenerateChangelogMain.SOURCE}, run DevelopmentMainForRelease."
    )
  }
}
