/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":projectforge-business"))
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.org.springframework.boot.starter.webflux)
    api(libs.jakarta.ws.rs.api)
    api(libs.com.google.zxing.core)
    api(libs.com.google.zxing.javase)
    testImplementation(project(":projectforge-commons-test"))
    testImplementation(testFixtures(project(":projectforge-business")))
    testImplementation(libs.com.google.code.gson)
    compileOnly(libs.javax.validation.validation.api)
    compileOnly(libs.jakarta.annotation.api)
    testImplementation(libs.org.junit.jupiter.api)
    testRuntimeOnly(libs.org.junit.jupiter.engine)
}

description = "projectforge-rest"
