= ProjectForge - project management solution

ProjectForge is a web-based solution for project management including time tracking, team calendar, gantt-charting, financial administration, issue management,
controlling and managing work-break-down-structures (e. g. together with JIRA as issue management system).

== Documentation of Docker (in progress)

=== With built-in data base HsqlDB:
1. Checkout: +
   https://github.com/micromata/projectforge.git
2. Build ProjectForge in main directory: +
   `mvn clean install -DskipTests`
3. Run build script in this directory: +
   `./buildDocker.sh`
4. Create any new directory you want as ProjectForge working directory in your host system: +
   `mkdir ~/ProjectForgeDocker`
5. Run ProjectForge and enjoy: +
   `docker run -t -i -p 127.0.0.1:8080:8080 -v ~/ProjectForgeDocker:/ProjectForge micromata/projectforge

=== With external PostgreSQL
tbd.

=== Putting all together (ProjectForge, Nginx and PostgreSQL)
1. Go to sub-directory +
   `cd compose`

tbd.



=== FAQ

- *Can't access port 8080?* +
  The built-in main `application.properties` defines `server.address=localhost`, therefore this port can't be exported to the host system. The Dockerfile of
  ProjectForge attaches an additional `application.properties` to the container which overrides `server.address=0.0.0.0`. +
  Through the `docker run` option `-p 8080:8080` the port is exported to the host.
