/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":projectforge-wicket"))
    api(project(":projectforge-rest"))
    testImplementation(testFixtures(project(":projectforge-business")))
    testImplementation(libs.jakarta.servlet.api)
}

description = "org.projectforge.plugins.todo"
