/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
}

dependencies {
    api(project(":projectforge-rest"))
    api(project(":org.projectforge.plugins.datatransfer"))
    api(libs.fr.opensagres.xdocreport.fr.opensagres.poi.xwpf.converter.pdf)
    testImplementation(project(":projectforge-business"))
    testImplementation(libs.org.postgresql.postgresql)
}

description = "org.projectforge.plugins.merlin"
