version: "3.8"
services:
  projectforge-app:
    image: micromata/projectforge:latest
    container_name: projectforge-app
    restart: always
    environment:
      # DOCKER_OPTS: so don't offer embedded database in setup wizard:
      - DOCKER_OPTS="-Ddocker=stack"
      #- DB_HOST=${DB_HOST}
      #- DB_PORT=${DB_PORT}
      #- POSTGRES_USER=${POSTGRES_USER}
      #- POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      #- POSTGRES_DB=${POSTGRES_DB}
    ports:
      #- "127.0.0.1:${APP_PORT}:8080"
      - "${APP_PORT}:8080"
    #volumes:
    #  - ${HOME}/ProjectForge:/ProjectForge
  depends_on:
      - projectforge-db

  projectforge-db:
    image: postgres:13.18
    container_name: projectforge-db
    restart: always
    #ports:
    #  - "127.0.0.1:5432:5432"
    volumes:
      - ./ProjectForgeDB:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/ssl/certs
      - ./nginx/keys:/etc/ssl/private
    depends_on:
      - projectforge-app
