ALTER TABLE t_user_pref ADD COLUMN IF NOT EXISTS value_string VARCHAR(100000);
ALTER TABLE t_user_pref ADD COLUMN IF NOT EXISTS value_type VARCHAR(1000);
ALTER TABLE t_user_pref ALTER COLUMN area TYPE varchar(255);

ALTER TABLE t_book DROP COLUMN IF EXISTS task_id;
